#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T>
inline bool dpmin(T& a, T b)
{
    if (a > b)
    {
        a = b;
        return 1;
    }
    return 0;
}
template <class T>
inline bool dpmax(T& a, T b)
{
    if (a < b)
    {
        a = b;
        return 1;
    }
    return 0;
}

void solve(long long N, string S) {
    int ans = 0;
    for (int i = 0; i < N; i++) {
        set<char> X, Y;
        for (int x = 0; x < i; x++) {
            X.insert(S[x]);
        }
        for (int y = i; y < N; y++) {
            Y.insert(S[y]);
        }

        // set and operation
        set<char> XY;
        set_intersection(X.begin(), X.end(), Y.begin(), Y.end(), inserter(XY, XY.end()));

        dpmax(ans, (int)XY.size());
    }

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use
// the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    cin >> N;
    string S;
    cin >> S;
    solve(N, S);
    return 0;
}
