/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class BCutAndCount {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      string s;
      in >> n >> s;
      int ans = 0;
      REP(i, n - 1) {
        string t1 = s.substr(0, i + 1);
        string t2 = s.substr(i + 1, s.length() - i - 1);
        int t = 0;
        map<char, int> m1, m2;
        REP(i, t1.length()) m1[t1[i]]++;
        REP(i, t2.length()) m2[t2[i]]++;
        REP(i, 26) {
          if (m1[i + 'a'] > 0 && m2[i + 'a'] > 0) {
            t++;
          }
        }
        ans = max(ans, t);
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BCutAndCount solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
