#include <bits/stdc++.h>
using namespace std;

void solve(long long N) {
	for(long long  A=1;A<=3500;A++) {
		for(long long B=A;B<=3500;B++) {
			long long P=4*A*B-N*(A+B);
			long long Q=N*A*B;
			if(P<=0) continue;
			if(Q%P) continue;
			cout<<A<<" "<<B<<" "<<Q/P<<endl;
			return;
        }
        }
    }
// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  solve(N);
  return 0;
}


