#include <bits/stdc++.h>
using namespace std;
#define rep(i,n) for(int i=0;i<(ll)(n);i++)
#define REP(i,m,n) for(int i=m;i<(ll)(n);i++)
typedef pair<int,int> pint;
typedef long long ll;

void solve(ll N){
    bool ok=false;
    REP(i,1,3501){
        REP(j,1,3501){
            if (ok) break;
            ll a = N*i*j;
            ll b=4*i*j-N*i-N*j;
            if(0<b && a%b==0){
                cout<<i<<" "<<j<<" "<<a/b<<endl;
                ok=true;
            }
        }
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    ll N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
