#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, long long L)
{
    auto taste_min = L;
    auto taste_max = L + N - 1;
    auto sum = (taste_min + taste_max) * N / 2;

    if (taste_min > 0) {
        sum -= taste_min;
    } else if (taste_max < 0) {
        sum -= taste_max;
    }
    cout << sum << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
#pragma GCC diagnostic ignored "-Wunused-result"
int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
    long long N;
    scanf("%lld",&N);
    long long L;
    scanf("%lld",&L);
    solve(N, L);
    return 0;
}
