/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author CompuWare
 */

#include <iostream>
#include <fstream>

#include <iostream>

class BBiteEating {
public:
    void solve(std::istream &in, std::ostream &out) {
        int64_t N, L, sum = 0;
        in >> N >> L;
        bool f = 1;
        for (int i = 1; i <= N; i++) {
            if ((L + i - 1 >= 0 && f) || (f && i == N)) {
                f = 0;
            } else sum += (L + i - 1);
//	         out << (L+i-1) << " ";
        }
        out << sum;
    }
};


int main() {
    BBiteEating solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
