/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"
using namespace std;
#define MOD 1000000007
//#define MOD 998244353
const double EPS = 1e-9;
#define INF (1LL<<60)
#define D double
#define fs first
#define sc second
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define RFOR(i,a,b) for(int i = (int)(b-1);i>=(int)(a);--i)
#define REP(i,n)  FOR(i,0,(n))
#define RREP(i,n) RFOR(i,0,(n))
#define ITR(itr,mp) for(auto itr = (mp).begin(); itr != (mp).end(); ++itr)
#define RITR(itr,mp) for(auto itr = (mp).rbegin(); itr != (mp).rend(); ++itr)
#define range(i,a,b) ((a)<=(i) && (i)<(b))
#define debug(x)  cout << #x << " = " << (x) << endl;
#define SP << " " <<
#define outdicimal out << fixed << setprecision(10)//TODO 小数点以下の桁数の変更
typedef pair<int,int> P;
typedef vector<int> vec;
typedef vector<vector<int>> mat;


class BBiteEating {
public:
	void solve(std::istream& in, std::ostream& out) {
	  int n,l;
	  in >> n >> l;
	  vec a(n);
	  int sum = 0;
	  FOR(i, 1, n + 1){
      a[i - 1] = l + i - 1;
      sum += a[i - 1];
	  }
    int min_t = INF;
	  int sub = 0;
	  REP(i, n){
	    int t = 0;
	    REP(j, n){
	      if(i != j) t += a[j];
	    }
	    t = abs(t - sum);
	    if(t < min_t){
        sub = a[i];
	      min_t = t;
	    }
	  }
	  int ans = 0;
	  ITR(itr,a){
	    ans += *itr;
	  }
	  out << ans - sub << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BBiteEating solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
