#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::string S){
  for(long long i = 0; i < S.size(); i++) {
    cout << (char)('A' + ((S[i] - 'A') + N) % 26);
  }

  cout << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::string S;
  std::cin >> S;
    solve(N, S);
    return 0;
}
