#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::string S){
    string T;
    for(char c : S){
        int newc = (int)(c) + (N%26);
        if((char)(newc)>'Z') T += (char)(newc-'Z'+'A'-1);
        else T += (char)(newc);
    }
    cout << T << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}
