#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(string r, string g, string b)
{
    string sum_str;
    sum_str = r + g + b;
    long long sum;
    sum = stol(sum_str);
    if (sum % 4 == 0)
    {
        cout << "YES" << endl;
    }
    else
    {
        cout << "NO" << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    string r;
    string g;
    string b;
    cin >> r >> g >> b;
    solve(r, g, b);
    return 0;
}
