#include <iostream>
#include <string>
#include <cstdio>
#include <vector>
#include <stdio.h>
#include <algorithm>
#include <functional>
#include <queue>
#include <math.h>
#include <cmath>
#include <unordered_map>

#define rep(i,n) for (int i = 0; i < (n); ++i)
using namespace std;


const long long MOD = 1000000007;


// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    std::vector<long long> sum(N,0);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
        if(i==0){
            sum[i]=A[i];
        }else{
            sum[i]=sum[i-1]+A[i];
        }
        //cout<<sum[i]<<endl;
    }


    long long ans=0;
    long long tmp=0;
    rep(i,N){
        tmp=(sum[N-1]-sum[i])%MOD;
        
        ans+=(tmp*A[i]);
        ans%=MOD;
    }
    cout<<ans%MOD<<endl;
    return 0;
}
