#include <bits/stdc++.h>
using namespace std;

void solve(std::string S) {
    int head = std::stoi(S.substr(0, 2));
    int tail = std::stoi(S.substr(2, 2));
    if ( (head <= 12 && head >= 1) && (tail <= 12 && tail >= 1) ) {
        cout << "AMBIGUOUS" << endl;
    } else if ((head <= 12 && head >= 1) && !(tail <= 12 && tail >= 1)) {
        cout << "MMYY" << endl;
    } else if (!(head <= 12 && head >= 1) && (tail <= 12 && tail >= 1)) {
        cout << "YYMM" << endl;
    } else {
        cout << "NA" << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  std::string S;
  std::cin >> S;
  solve(S);
  return 0;
}
