#include <bits/stdc++.h>
using namespace std;
using ll = long long;

bool month(int mm)
{
    return (1 <= mm && mm <= 12);
}

void solve(std::string S)
{
    int th = stoi(S.substr(0, 2));
    int bh = stoi(S.substr(2, 2));
    if (month(th) && month(bh)) {
        cout << "AMBIGUOUS\n";
    } else if (month(th) && !month(bh)) {
        cout << "MMYY\n";
    } else if (!month(th) && month(bh)) {
        cout << "YYMM\n";
    } else {
        cout << "NA\n";
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
