#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long B)
{
    if (A > B)
    {
        cout << A + (A - 1) << endl;
    }
    else if (A == B)
    {
        cout << A + B << endl;
    }
    else
    {
        cout << B + (B - 1) << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    solve(A, B);
    return 0;
}
