#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";
const string AKIBA = "AKIHABARA";
void solve(std::string S){
  for(long long i = 0; i < AKIBA.size(); i++) {
    if(S.size() <= i && S.size() < AKIBA.size()) S.push_back('A');
    else if(AKIBA[i] == 'A' && S[i] != 'A') S.insert(i, "A");
  }

  cout << ((S == AKIBA) ? YES : NO) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
    solve(S);
    return 0;
}
