#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG

const string YES = "YES";
const string NO = "NO";

bool isOk2(int r, int c, ll H, ll W){
    if(c < 0){
        return false;
    }
    if(c >= W){
        return false;
    }
    if(r < 0){
        return false;
    }
    if(r >= H){
        return false;
    }
    return true;
}

bool char2row(char c){
    if(c == 'U'){
        return -1;
    }
    if(c == 'D'){
        return +1;
    }
    return 0;
}

bool char2col(char c){
    if(c == 'L'){
        return -1;
    }
    if(c == 'R'){
        return 1;
    }
    return 0;
}


void solve(long long H, long long W, long long N, long long s_r, long long s_c, std::string S, std::string T){
    int deathL = -1;
    int deathR = W;
    int deathU = -1;
    int deathD = H;
    s_r--;
    s_c--;
    for(int i=N-1; i >= 0; i--){
        if(T.at(i) == 'L' && deathR < W){
            deathR++;
        }else if(T.at(i) == 'R' && deathL > -1){
            deathL--;
        }else if(T.at(i) == 'U' && deathD < H){
            deathD++;
        }else if(T.at(i) == 'D' && deathU > -1){
            deathU--;
        }

        if(S.at(i) == 'L'){
            deathL++;
        }else if(S.at(i) == 'R'){
            deathR--;
        }else if(S.at(i) == 'U'){
            deathU++;
        }else if(S.at(i) == 'D'){
            deathD--;
        }

        if(deathL == W-1 || deathR == 0 || deathU == H-1 || deathD == 0){
            cout << NO << endl;
            return;
        }
    }

    if(s_r <= deathU || s_r >= deathD || s_c <= deathL || s_c >= deathR){
        cout << NO << endl;
        return;
    }

    cout << YES << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    scanf("%lld",&H);
    long long W;
    scanf("%lld",&W);
    long long N;
    scanf("%lld",&N);
    long long s_r;
    scanf("%lld",&s_r);
    long long s_c;
    scanf("%lld",&s_c);
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(H, W, N, s_r, s_c, S, T);
    return 0;
}
