/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class BContestWithDrinksEasy {
public:
    void solve(istream& cin, ostream& cout) {
        int n; cin >> n; ll sum =0;
        vector<int> t; for(int i=0; i<n; i++) {int tp; cin >> tp; t.push_back(tp); sum += tp;}
        int m; cin >> m;
        for(int i=0; i<m ;i++) {
            int p, x; cin >> p >> x;
            p--;
            cout << sum - t[p] + x << '\n';
        }
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    BContestWithDrinksEasy solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
