#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A){
  A.erase(unique(A.begin(), A.end()), A.end());

  long long ans = 1;

  for(long long i = 1; i < (A.size()-1); i++){
    if(A[i-1] < A[i] && A[i] > A[i+1] ||
       A[i-1] > A[i] && A[i] < A[i+1]) {
      ans++;
      i++;
    }
  }

  cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> A(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&A[i]);
  }
    solve(N, std::move(A));
    return 0;
}
