/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author rahdirigs
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

template <typename T> void s_max(T& a, T b) {
	if (a < b) {
		a = b;
	}
}

const int mxN = 1010, mxW = 2e4 + 5;
ll dp[mxN][mxW];

class TaskX {
public:
	struct block {
		int w, s, v;

		void input(istream& in) {
			in >> w >> s >> v;
		}

		ll param() const {
			return (s + w);
		}
	};

	block a[mxN];
	int N;

	void solve(std::istream& in, std::ostream& out) {
		in >> N;
		for (int i = 0; i < N; i++) a[i].input(in);
		sort(a, a + N, comp);
		memset(dp, -1, sizeof(dp));
		ll ans = rec(0, 0);
		out << ans;
	}

	static bool comp(const block& b1, const block& b2) {
		return (b1.param() < b2.param());
	}

	ll rec(int n, int wt) {
		if (n == N) {
			return 0;
		}
		if (dp[n][wt] != -1) return dp[n][wt];
		dp[n][wt] = rec(n + 1, wt);
		if (a[n].s >= wt) {
			s_max(dp[n][wt], a[n].v + rec(n + 1, a[n].w + wt));
		}
		return dp[n][wt];
	}
};

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	TaskX solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
