#include <bits/stdc++.h>
using namespace std;

void solve(std::string S) {
  int n = S.length();
  int ans = 0;
  for (int i = 0; i < n / 2; i++) {
    if (S[i] != S[n - 1 - i]) ans++;
  }
  cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  std::string S;
  std::cin >> S;
  solve(S);
  return 0;
}
