#include <bits/stdc++.h>
using namespace std;


void solve(std::string S){
 long long N = S.size();
 long long count = 0;

 for(long long i = 0; i < N/2; i++){
   if(S[i] != S[(N-1)-i]) count++;
 }

 cout << count << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
    solve(S);
    return 0;
}
