#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A){
  long long count = 0;
  for(long long i = 0; i < (1<<(N*2)); i++) {
    bool similar = true;
    long long acc = 1;
    for(long long j = 0; j < N; j++) {
      long long current = (i&(0b11<<(j*2)))>>(j*2);
      if(current == 0b11) similar = false;
      acc *= ((A[j]+(current-1)) % 2);
    }

    if(similar && acc == 0) count++;
  }

  cout << count << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> A(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&A[i]);
  }
    solve(N, std::move(A));
    return 0;
}
