#include <bits/stdc++.h>
using namespace std;


void solve(long long N){
  long long digit = floor(log(N)/log(10));
  long long acc = N;
  bool allnine = true;

  for(int i = 0; i < digit; i++){
    if (acc % 10 != 9) allnine = false;
    acc /= 10;
  }

  if(!allnine) acc -= 1;


  for(int i = 0; i < digit; i++){
    acc += 9;
  }
  cout << acc << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
    solve(N);
    return 0;
}
