/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>

#define pb push_back
#define sz(v) ((int)(v).size())
#define all(v) (v).begin(),(v).end()
#define mp make_pair
#define N 1000010
using namespace std;
typedef long long ll;
typedef long long int64;
typedef vector<int> vi;
typedef pair<int, int> ii;
ll a[N];
int p=2;
ll pow(ll y,int z,int p){
    y%=p;ll ans=1;
    for(int i=z;i;i>>=1,y=y*y%p)if(i&1)ans=ans*y%p;
    return ans;
}
ll C(ll n,ll m){
    if(m>n)return 0;
    return ((a[n]*pow(a[m],p-2,p))%p*pow(a[n-m],p-2,p)%p);
}
ll Lucas(ll n,ll m){
    if(!m)return 1;
    return C(n%p,m%p)*Lucas(n/p,m/p)%p;
}
inline int read(){
    int f=1,x=0;char ch;
    do{ch=getchar();if(ch=='-')f=-1;}while(ch<'0'||ch>'9');
    do{x=x*10+ch-'0';ch=getchar();}while(ch>='0'&&ch<='9');
    return f*x;
}
class TaskB {
 public:
  int innerSolve(int n, const vector<int>& a) {
    int res = 0;
    for (int i = 0; i < n; ++i) {
//      if (((n - 1) & i) == i) {
//        res ^= a[i];
//      }
		if(Lucas(n-1,i))res ^= a[i];
    }
    return res;
  }

  void solveOne(istream &in, ostream &out) {
    int n;
    string s;
    in >> n;
    in >> s;
    vector<int> a(n);
    for (int i = 0; i < n; ++i) {
      a[i] = s[i] - '1';
    }
    bool anyOnes = false;
    for (int x : a) if (x == 1) anyOnes = true;
    if (anyOnes) {
      for (int i = 0; i < n; ++i) if (a[i] == 2) a[i] = 0;
      out << innerSolve(n, a) << "\n";
    } else {
      for (int i = 0; i < n; ++i) if (a[i] == 2) a[i] = 1;
      out << 2 * innerSolve(n, a) << "\n";
    }
  }

  void solve(std::istream &in, std::ostream &out) {
    int nt;
    nt = 1;
    for (int it = 0; it < nt; ++it) {
      solveOne(in, out);
    }
  }
};


int main() {
  ios_base::sync_with_stdio(false);
  cin.tie(NULL);
  TaskB solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  a[0]=1;
  for(int i=1;i<=p;i++)a[i]=(a[i-1]*i)%p;
  solver.solve(in, out);
  return 0;
}
