#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)

//long long hornest_search(long long bit, vector<vector<pair<long long, long long>>>)
bool honest_search(long long bit, vector<vector<pair<long long, long long>>> x_y, long long N)
{
    //i番目の人の発言を基にhonestを探す。
    for (long long i = 0; i < N; i++)
    {
        //bit & (1 << i) を使うことで、半自動的に全部の通りを割り当てている。
        // 11010101 ~ 0番目の人:正直,1の人:不親切,2の人:正直,3:不親切....
        //search対象がhonestではない場合
        if (!(bit & (1 << i)))
            continue;

        //i番目の人の証言確認
        for (pair<long long, long long> xy : x_y[i])
        {
            int x = xy.first;  //x番目の人が
            int y = xy.second; //0 or 1

            //iの話では不親切(y=1)だが,<bitset>(8)では正直者扱い
            if (y == 1 && !(bit & (1 << x)))
                return false;

            //iの話では正直(y=0)だが,bitでは不親切扱い
            if (y == 0 && (bit & (1 << x)))
                return false;

            //完全に一致するデータは一つだけ?
            //bitは2^N通りであり,その分だけ繰り返しているだけ,
        }
    }
    //正直者と嘘つきの分け方は,全ての証言+bitの照らし合わせで決まる。
    //なので,return trueはfor抜けた後、
    return true;
}

int main()
{
    long long N;
    cin >> N;

    vector<vector<pair<long long, long long>>> x_y(N);
    for (int i = 0; i < N; i++)
    {
        long long A;
        cin >> A;
        //x_y[i].resize(A);
        for (int j = 0; j < A; j++)
        {
            long long x, y;
            cin >> x >> y;
            x_y[i].push_back({x - 1, y}); //x_y[i][j].first >> x_y[i][j].secondでもok
            //cin >> x_y[i][j].first >> x_y[i][j].second;
            //--x_y[i][j].first; // 0-indexed に
        }
    }

    //bit < 2^N

    long long max_h = 0;
    for (long long bit = 0; bit < (1 << N); bit++)
    {
        if (honest_search(bit, x_y, N))
        {
            long long count = 0;
            for (int i = 0; i < N; i++)
            {
                if (bit & (1 << i))
                {
                    count++;
                }
            }
            max_h = max(max_h, count);
        }
    }
    cout << max_h << endl;
}