#include <bits/stdc++.h>
#define rep(i, n) for (int i = 0; i < (n); ++i)
using namespace std;
using P = pair<int, int>;

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  int n;
  cin >> n;
  vector<int> a(n);
  vector<vector<P> > vec(n);
  rep(i, n) {
    cin >> a[i];
    int x, y;
    rep(_, a[i]) {
      cin >> x >> y;
      vec[i].push_back(make_pair(x - 1, y));
    }
  }
  int ans = 0;
  for (int i = 0; i < (1 << n); i++) {
    bitset<15> s(i);
    bool contradiction = false;
    rep(j, n) {
      if (s.test(j)) {
        rep(k, a[j]) {
          P p = vec[j][k];
          if ((p.second ^ s[p.first]) == 1) {
            contradiction = true;
            break;
          }
        }
      }
      if (contradiction) break;
    }
    if (!contradiction) {
      ans = max((int)s.count(), ans);
    }
  }
  cout << ans << endl;
  return 0;
}
