#include <bits/stdc++.h>
using namespace std;

void solve(std::string s) {
	if((s.size()%2 == 0) ^ (s[0] == s[s.size()-1]))cout<<"Second";
  else cout<<"First";
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  std::string s;
  std::cin >> s;
  solve(s);
  return 0;
}
