#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long K){
  for(int i = A; i <= B; i++) {
    if((A+K) > i || (B-K) < i) cout << i << endl;
  }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long K;
  scanf("%lld",&K);
    solve(A, B, K);
    return 0;
}
