/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))
#define ITR(itr,mp) for(auto itr = (mp).begin(); itr != (mp).end(); ++itr)


class BSmallAndLargeIntegers {
public:
	void solve(std::istream& in, std::ostream& out) {
    int a,b,k;
    in >> a >> b >> k;
    set<int> s;
    REP(i, min(k, b - a + 1)){
      s.insert(a + i);
    }
    REP(i, min(k, b - a + 1)){
      s.insert(b - i);
    }
    ITR(itr, s){
      out << *itr << endl;
    }
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BSmallAndLargeIntegers solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
