/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class BSmallAndLargeIntegers {
public:
    void solve(istream& cin, ostream& cout) {
        ll a, b, k;
        cin >> a >> b >> k;
        ll e1 = a+k-1, s2 = b+1-k;
        if(s2 > e1) {
            for(int i=a; i<=e1; i++) cout << i << '\n';
            for(int i=s2; i<=b; i++) cout << i << '\n';
        } else
            for(int i=a; i<=b; i++) cout << i << '\n';
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    BSmallAndLargeIntegers solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
