#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;
ll N;
map<ll,ll> mp;
vector<ll> A;
vector<ll> dp;

ll dfs(int t){
    if(dp[t] != -1){
        return dp[t];
    }
    if(t == N-1){
        dp[t] = 1;
        return 1;
    }
    ll v = A[t];
    if(v ==N){
        dp[t] = 1;
        return 1;
    }
    if(mp[v+1] <t){
        return 1;
    }
    dp[t] = dfs(mp[v+1])+1;
    // cerr <<"t=" <<t <<"v= " << v <<"dp=" << dp[t] << endl;
    return dp[t];

}

void solve(){
    for(int i=0;i<N;i++){
        mp[A[i]] =i;
    }
    dp.resize(N,-1);
    ll ans =0;
    for(int i=0;i<N;i++){
        ans = max(ans,dfs(i));
    }
    cout << N-ans << endl;

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    scanf("%lld",&N);
    A.resize(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve();
    return 0;
}
