#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)


void solve(long long N, std::vector<long long> P){
    vector<ll> num(N, 0);
    REP(i, N){
        ll pi = P.at(i);
        pi--;
        if(pi == 0){
            num.at(pi) = 1;
        }else{
            if(num.at(pi - 1) > 0){
                num.at(pi) = num.at(pi - 1) + 1;
            }else{
                num.at(pi) = 1;
            }
        }
    }
    cout << N - *max_element(num.begin(), num.end()) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> P(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&P[i]);
    }
    solve(N, std::move(P));
    return 0;
}
