#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> P){
    map<int, int> mp;
    for(int i = 0; i < N; i++) {
        mp[P[i]] = i;
    }

    vector<int> q(N + 1, 0);
    for(int i = 0; i < N; i++) {
        if(i < mp[P[i] + 1]) q[P[i]] += q[P[i] - 1] + 1;
    }

    int ans = 0;
    for(auto e: q) ans = max(e, ans);
    cout << N - ans - 1 << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> P(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&P[i]);
        P[i];
    }
    solve(N, std::move(P));
    return 0;
}
