#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T>
inline bool dpmin(T& a, T b)
{
    if (a > b)
    {
        a = b;
        return 1;
    }
    return 0;
}
template <class T>
inline bool dpmax(T& a, T b)
{
    if (a < b)
    {
        a = b;
        return 1;
    }
    return 0;
}

void solve(long long N, vector<long long> x, vector<long long> y) {

    vector<int> order(N);
    rep(i, N) order[i] = i;

    int n_perm = 1;
    rep(i, N) n_perm *= i + 1;

    double ans = 0;
    do {
        double dist = 0;
        for (int i = 1; i < N; i++) {
            dist = sqrt(pow(x[order[i-1]] - x[order[i]], 2.0) + pow(y[order[i-1]] - y[order[i]], 2.0));
            /* cout << dist << endl; */
            ans += dist;
        }
    } while (next_permutation(order.begin(), order.end()));

    ans /= (double)n_perm;
    printf("%lf\n", ans);
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use
// the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    cin >> N;
    vector<long long> x(N);
    vector<long long> y(N);
    for (int i = 0; i < N; i++)
    {
        cin >> x[i];
        cin >> y[i];
    }
    solve(N, move(x), move(y));
    return 0;
}
