/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author rahdirigs
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

template <typename T> void s_max(T& a, T b) {
	if (a < b) {
		a = b;
	}
}

struct segtree {
	int l, r, mid;
	ll val;
	segtree *left, *right;

	segtree(int _l, int _r) {
		l = _l;
		r = _r;
		val = 0;
		mid = l;
		if (l != r) {
			mid = l + (r - l) / 2;
			left = new segtree(l, mid);
			right = new segtree(mid + 1, r);
		}
	}

	void update(int pos, ll v) {
		if (l == r) {
			val = v;
		} else {
			if (pos <= mid) {
				left -> update(pos, v);
			} else {
				right -> update(pos, v);
			}
			val = max(left-> val, right -> val);
		}
	}

	ll query(int ql, int qr) {
		if (ql > r || qr < l) return 0;
		if (ql <= l && qr >= r) return val;
		return max(left -> query(ql, qr), right -> query(ql, qr));
	}
};

class TaskQ {
public:
	void solve(std::istream& in, std::ostream& out) {
		int N;
		in >> N;
		vector<int> h(N), a(N);
		for (int i = 0; i < N; i++) in >> h[i];
		for (int i = 0; i < N; i++) in >> a[i];
		segtree tree = segtree(0, N);
		ll ans = 0;
		for (int i = 0; i < N; i++) {
			ll val = tree.query(0, h[i] - 1) + a[i];
			s_max(ans, val);
			tree.update(h[i], val);
		}
		out << ans;
	}
};

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	TaskQ solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
