#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::string S) {
int B = count(S.begin(), S.end(), '#');
int W = count(S.begin(), S.end(), '.');
int ans = min(B, W);
  int b = 0;
  int w = 0;
  for(int i = 0 ; i < N ; i++){
  	if(S[i] == '#' ) b++;
    else w++;
    ans = min(ans, b + W - w);
  }
  cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  std::string S;
  std::cin >> S;
  solve(N, S);
  return 0;
}
