#include <bits/stdc++.h>
using namespace std;


void solve(std::string S){
  long long N = S.size();
  vector<vector<long long>> dp(N, vector<long long>(2));
  dp[0][0] = 1;

  if(N >= 2) {
    if (S[0] != S[1]) {
      dp[1][0] = 2;
    }
    else {
      dp[1][1] = 1;
    }
  }
  if(N >= 3) {
    if (S[1] != S[2]) {
      dp[2][0] = max(dp[1][0], dp[1][1]) + 1;
    }
    else {
      dp[2][0] = 2;
    }
  }

  for(long long i = 3; i < N; i++) {
    if(S[i] != S[i-1]) {
      dp[i][0] = max(dp[i-1][0], dp[i-1][1]) + 1;
    }
    else {
      dp[i][1] = max(dp[i-3][0], dp[i-3][1]) + 2;
    }
  }

  cout << *max_element(dp[N-1].begin(), dp[N-1].end()) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
    solve(S);
    return 0;
}
