services:
  - type: web
    name: codeinsight-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        value: ep-plain-moon-azp8k1wn.c-3.ap-southeast-1.aws.neon.tech
      - key: DB_NAME
        value: codeinsight
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_SSL
        value: "true"
      - key: DB_CONNECTION_TIMEOUT_MS
        value: "5000"
      - key: REDIS_HOST
        value: tough-akita-173554.upstash.io
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: CORS_ORIGINS
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: EMAIL_ENABLED
        value: "true"
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM_ADDRESS
        value: codeinsight.noreply@gmail.com
      - key: EMAIL_FROM_NAME
        value: CodeInsight
    healthCheckPath: /api/ready