#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long A, long long B){
  if(abs(A-B)%2 == 0) {
    cout << (abs(A-B)/2) << endl;
  }
  else if((min(A, B) - 1) < (N - max(A, B))) {
    cout << (min(A, B) - 1) + (abs((A-1) - B) / 2) << endl;
  }
  else {
    cout << (N - max(A, B)) + (abs(A - (B+1)) / 2) << endl;
  }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
    solve(N, A, B);
    return 0;
}
