#include <bits/stdc++.h>
using namespace std;

void solve(long long N, long long A, long long B) {
    if (!(A < B)) {
        swap(A, B);
    }
    if (B % 2 == A % 2) {
        cout << (B - A) / 2LL << endl;
        return;
    }

    long long ans = numeric_limits<long long>::max();

    auto a = A, b = B;
    // left
    auto l = (a - 1LL);
    b -= l;
    a -= l;
    b--;
    ans = min(ans, l + 1LL + (b - a) / 2LL);

    // right
    a = N - A + 1;
    b = N - B + 1;
    l = (a - 1LL);
    b -= l;
    a -= l;
    b--;
    ans = min(ans, l + 1LL + (b - a) / 2LL);

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
    long long N;
    scanf("%lld", &N);
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    solve(N, A, B);
    return 0;
}
