#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
const long long MOD = 1000000007;

template<typename T>
std::map<T,T> prime_factor(T n){
  std::map<T,T> res;
  for (T i=2;i*i<=n;i++){
    while( n%i == 0){
      ++res[i];
      n/=i;
    }
  }
  if (n!=1) res[n] = 1;
  return res;

}

template<typename T >
T modpow(T a, T n, T mod) {
    T res = 1;
    while (n > 0) {
        if (n & 1) res = res * a % mod;
        a = a * a % mod;
        n >>= 1;
    }
    return res;
}

void solve(long long N){
    map<ll,ll> factors;
    for (ll i=2;i<=N;i++){
        map<ll,ll> a = prime_factor(i);
        for (auto const& obj : a){
            ll k = obj.first;
            ll v = obj.second;
            factors[k]+=v;
        }

    }
    
    if (N == 1){
        printf("1\n");
    }else{
        ll ret = 1;
        for (auto const& obj : factors){
            ll k = obj.first;
            ll v = obj.second;
            ret*= v+1;
            ret %=MOD;
        }
        printf("%lld\n",ret%MOD);
    }


}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
