#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long x, long long y){
  set<long long> st1({1, 3, 5, 7, 8, 10, 12});
  set<long long> st2({4, 6, 9, 11});
  set<long long> st3({2});

  if(st1.count(x) > 0 && st1.count(y) > 0) cout << YES << endl;
  else if(st2.count(x) > 0 && st2.count(y) > 0) cout << YES << endl;
  else if(st3.count(x) > 0 && st3.count(y) > 0) cout << YES << endl;
  else cout << NO << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long x;
  scanf("%lld",&x);
  long long y;
  scanf("%lld",&y);
    solve(x, y);
    return 0;
}
