#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long X, std::vector<long long> L){
  long long acc = 0;
  long long count = 0;

  for(long long i = 0; i < N; i++){
    if(acc + L[i] > X) {
      break;
    }

    acc += L[i];
    count++;
  }

  cout << count+1 << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  long long X;
  scanf("%lld",&X);
  std::vector<long long> L(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&L[i]);
  }
    solve(N, X, std::move(L));
    return 0;
}
