#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG

ll sub(ll n, vec<ll>& a, int sign){
    ll currentSum = 0;
    ll numOps = 0;
    for(int i=0; i < n; i++){
        ll nextSum = currentSum + a.at(i);
        if(nextSum*sign > 0){
            // そのまま
            // currentSum = nextSum;
        }else{
            // cout << "violated" << nextSum << endl;
            numOps += abs(sign - (currentSum + a.at(i)));
            nextSum = sign;
        }
        currentSum = nextSum;
        sign *= -1;
        // cout << currentSum << " " << numOps  << endl;
    }
    return numOps;

}

void solve(long long n, std::vector<long long> a){
    ll pos = sub(n, a, 1);
    ll neg = sub(n, a, -1);
    // cout << pos << " " << neg << endl;
    cout << min(pos, neg) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long n;
    scanf("%lld",&n);
    std::vector<long long> a(n);
    for(int i = 0 ; i < n ; i++){
        scanf("%lld",&a[i]);
    }
    solve(n, std::move(a));
    return 0;
}
