/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class ADiagonalString {
public:
	void solve(std::istream& in, std::ostream& out) {
    vector<vector<char>> c(3, vector<char>(3));
    REP(i,3)REP(j,3){
      in >> c[i][j];
    }
    string s({c[0][0], c[1][1], c[2][2]});
    out << s << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	ADiagonalString solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
