/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define rep(i, n)           for (int i = 0; i < (int)(n); i++)
#define REP(i, a, b)        for (int i = (int)(a); i < (int)(b); i++)
#define FOR(i, a)           for (auto &i : a)
#define ALL(obj)            begin(obj), end(obj)
#define MAX(x)              *max_element(ALL(x))
#define MIN(x)              *min_element(ALL(x))
#define sum(x)              accumulate(ALL(x), 0LL)
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))

using namespace std;
const int MOD    = (int)(1e9 + 7);
const int INF    = (int)(1e13 + 7);
const double EPS = 1e-14;
const double PI  = acos(-1);

int CEIL(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); } //ceil() for int
int mod(int a, int b) { return a >= 0 ? a % b : a - (b * CEIL(a, b)); }             //always return positive num
int bpm(int a, int b) {                                                             //return x^y in order(log(y))
  int res = 1;
  for (a %= MOD; b; a = a * a % MOD, b >>= 1)
    if (b & 1) res = res * a % MOD;
  return res;
}
vector<vector<pair<int, int>>> graph(100000);
vector<int> color(100000, 0);

void paint(int now) {
  FOR(i, graph[now]) {
    if (color[i.first] != 0) continue;
    if (i.second % 2) {
      color[i.first] = color[now] * -1;
      paint(i.first);
    } else {
      color[i.first] = color[now];
      paint(i.first);
    }
  }
}

class DEvenRelation {
public:
  static void solve(istream &cin, ostream &cout) {
    int N;
    cin >> N;
    rep(i, N - 1) {
      int u, v, w;
      cin >> u >> v >> w;
      graph[u - 1].emplace_back(v - 1, w);
      graph[v - 1].emplace_back(u - 1, w);
    }
    color[0] = 1;
    paint(0);
    rep(i, N) {
      if (color[i] == 1) {
        cout << 0 << endl;
      } else {
        cout << 1 << endl;
      }
    }
  }
};


signed main() {
  cin.tie(0);
  cout.tie(0);
  ios_base::sync_with_stdio(false);
  cout<<fixed<<setprecision(15);
  DEvenRelation solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
