#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;

void solve(long long N, std::vector<long long> A){
    multiset<ll> s;
    for(int i=0;i<N;i++){
        auto itr = s.lower_bound(A[i]);
        if(itr == s.begin()){
            // cerr <<"*itr=" << *itr<< endl;
            s.insert(A[i]);
        }else{
            --itr;
            s.erase(itr);
            s.insert(A[i]);
        }
    }
    cout << s.size() << endl;

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
