#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

void solve_sub(ll N){
    cout << (N / 2) * 4 << endl;

    const ll M = N - N % 2;
    vector<vector<ll>> vs;
    REP(i, M / 2){
        vs.push_back({i + 1, M - i});
    }
    if(N % 2){
        vs.push_back({N});
    }

    REP(i, vs.size()){
        for(ll x : vs.at(i)){
            for(ll y : vs.at((i + 1) % vs.size())){
                cout << x << ' ' << y << endl;
            }
        }
    }
}

void solve(long long N){
    if(N == 3){
        cout << 2 << endl;
        cout << 1 << ' ' << 3 << endl;
        cout << 2 << ' ' << 3 << endl;
    }else if(N == 4){
        cout << 4 << endl;
        cout << 1 << ' ' << 2 << endl;
        cout << 1 << ' ' << 3 << endl;
        cout << 4 << ' ' << 2 << endl;
        cout << 4 << ' ' << 3 << endl;
    }else{
        solve_sub(N);
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
