#include <bits/stdc++.h>
using namespace std;
using ll = long long;

vector<ll> get_divisors(ll num)
{
    deque<ll> divisors;
    for (ll i = 1; i * i <= num; i++) {
        if (num % i == 0) {
            divisors.push_front(i);
            if (i * i < num) {
                divisors.push_back(num / i);
            }
        }
    }
    return vector<ll>(begin(divisors), end(divisors));
}

void solve(long long N)
{
    ll ans = 0;

    // K^m = N (m=1,2,3…)となるKの数
    auto divisors = get_divisors(N);
    for (auto d : divisors) {
        if (d > 1) {
            auto n = N;
            while (n % d == 0) {
                n /= d;
            }
            if (n % d == 1) {
                ans++;
            }
        }
    }

    // mK+1 = N (m=1,2,3…)となるKの数
    // K=(N-1)/mなので、N-1の約数の数-1だけ存在(-1するのはm=N-1の時はK=1となり、不適であるため)
    ans += get_divisors(N - 1).size() - 1;

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
#pragma GCC diagnostic ignored "-Wunused-result"
int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
