#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

vector<long long> topological_sort(vector<vector<ll>> &graph,vector<ll> &in_degrees){
    stack<ll> st;
    for (ll i=1;i<graph.size();i++){
        if (in_degrees[i] == 0) st.push(i);
    }
    vector<ll> ans;
    while(st.size()>0){
        auto i = st.top();st.pop();
        ans.push_back(i);
        for (auto &j:graph[i]){
            in_degrees[j] --;
            if (in_degrees[j] == 0) st.push(j);
        }
    }
    return ans;
}


void solve(long long N, long long M, std::vector<long long> A, std::vector<long long> B){
    //隣接リストを構築
    vector<vector<ll>> graph(N+1);    //グラフの頂点はN個    
    vector<vector<ll>> in_graph(N+1);
    vector<ll> in_degrees(N+1,0);
    for (ll i=0;i<A.size();i++){
        graph[A[i]].push_back(B[i]);
        in_graph[B[i]].push_back(A[i]);
        in_degrees[B[i]]+=1;
    }
    vector<ll> sorted_graph = topological_sort(graph,in_degrees);
    vector<ll> node_score(N+1);
    for (ll i=0;i<sorted_graph.size();i++){
        node_score[sorted_graph[i]] = i;
    }
    vector<ll> parents(N+1,0);
    for (ll i=1;i<=N;i++){
        ll maximum_node = 0;
        ll maximum_score = -1;
        for (const auto &j:in_graph[i]){
            if (maximum_score < node_score[j]){
                maximum_score = node_score[j];
                maximum_node = j;
            }
        }
        printf("%lld\n",maximum_node);
    }

    
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> A(N-1+M);
    std::vector<long long> B(N-1+M);
    for(int i = 0 ; i < N-1+M ; i++){
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
    }
    solve(N, M, std::move(A), std::move(B));
    return 0;
}
