#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)


void solve(long long N, long long M,
           std::vector<long long> A, std::vector<long long> B){
    vector<vector<ll>> net(N);
    vector<ll> indeg(N, 0);
    REP(i, A.size()){
        ll ai = A.at(i);
        ll bi = B.at(i);
        ai--; bi--;
        net.at(ai).push_back(bi);
        indeg.at(bi)++;
    }

    ll src = 0;
    REP(i, N){
        if(indeg.at(i) == 0){
            src = i;
            break;
        }
    }

    vector<ll> dist(N, -1);
    vector<ll> par(N, -1);
    queue<ll> que;
    que.emplace(src);
    dist.at(src) = 0;
    while(!que.empty()){
        ll v = que.front(); que.pop();
        for(ll nxt : net.at(v)){
            indeg.at(nxt)--;
            if(dist.at(nxt) < dist.at(v) + 1){
                dist.at(nxt) = dist.at(v) + 1;
                par.at(nxt) = v;
            }
            if(indeg.at(nxt) == 0){
                que.push(nxt);
            }
        }
    }

    REP(i, N){
        if(i == src){
            cout << 0 << endl;
        }else{
            cout << par.at(i) + 1 << endl;
        }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> A(N-1+M);
    std::vector<long long> B(N-1+M);
    for(int i = 0 ; i < N-1+M ; i++){
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
    }
    solve(N, M, std::move(A), std::move(B));
    return 0;
}
