#include <bits/stdc++.h>
using namespace std;
typedef long long ll;


bool is_bipartite(vector<vector<ll>> &link_list,vector<int>&color,ll node, int current_color){
    color[node] = current_color;
    for (const auto &next_node :link_list[node]){
        if (color[next_node] == current_color) return false;
        if (color[next_node] == 0 && !is_bipartite(link_list,color,next_node,-current_color)) return false;//dfsでfalseだったらfalseを返す
    }
    return true;
}


void solve(long long N, long long M, std::vector<long long> A, std::vector<long long> B){
    vector<vector<ll>> link_list(N+1);
    for (ll i = 0;i<M;i++){
        link_list[A[i]].push_back(B[i]);
        link_list[B[i]].push_back(A[i]);
    }
    vector<int> color(N+1,0);
    bool flag = is_bipartite(link_list,color,1,1);
    if (!flag){
        printf("%lld\n",N*(N-1)/2-M);
    }else{
        ll W = 0;
        for (const auto &c :color){
            if (c==1) W++;
        }
        ll B = N-W;
        printf("%lld\n",B*W-M);
    }
    

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> A(M);
    std::vector<long long> B(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
    }
    solve(N, M, std::move(A), std::move(B));
    return 0;
}
