#include <bits/stdc++.h>
using namespace std;

void solve(long long N, long long K)
{
    //int N K
    string ch = "";
    while (N >= K) //N % K != 0)
    {
        ch = to_string(N % K) + ch;
        N /= K;
    }
    //ch = to_string(N % K) + ch;
    //N /= K;
    ch = to_string(N) + ch;
    //cout << ch << endl;
    long long ssize = ch.size();

    cout << ssize << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    long long K;
    scanf("%lld", &K);
    solve(N, K);
    return 0;
}
