/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <limits.h>
#include <algorithm>
#include <bitset>
#include <cctype>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>

#include <list>
#include <map>
#include <numeric>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
#include <queue>
#include <unordered_map>
#include <unordered_set>

using namespace std;

typedef long long ll;

class DPairCards {
public:
	void solve(std::istream& cin, std::ostream& cout) {
		int n,m;cin >> n >> m;
		vector<int> G(m,0),GP(m,0),cnt(100010,0),pairs(100010,0);
		for (int i = 0; i < n; ++i)
		{
			int v;cin >> v;
			cnt[v]++;
		}
		for (int i = 0; i < 100010; ++i)
		{
			pairs[i] = cnt[i]/2;
			G[i%m] += cnt[i];
			GP[i%m] += pairs[i];
		}
		int left = 0;
		for (int i = 0; i < (m-i)+1; ++i)
		{
//			cout << i << " : " << G[i] << " " << GP[i] << endl;
//            cout << m - i << " : " << G[m - i] << " " << GP[m - i] << endl;
			if(i == m-i){
				left += G[i] % 2;
				break;
			}
			if(i == 0){
			    left += G[i] % 2;
			    continue;
			}
			if(G[i] <= G[m-i]){
				swap(G[i],G[m-i]);
				swap(GP[i],GP[m-i]);
			}
			int d = G[i] - G[m-i];
			left += max(0,d - min((d/2),GP[i])*2);
		}
//		cout << left << " ";
		cout << (n-left)/2 << endl;
	}
};


int main() {
	DPairCards solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
