/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author TM
 */


#include <iostream>
#include <algorithm>
#include <vector>
#include <string>
#include <queue>
#include <map>
#include <set>
#include <functional>
#include <cmath>
#include <numeric>
#include <iterator>
#include <fstream>

#define SIZE 100005
#define MOD 1000000007

using namespace std;

class CTsundoku {
public:
    static void solve(std::istream &cin, std::ostream &cout) {
        int64_t n, m, k;
        cin >> n >> m >> k;
        vector<int64_t> a_vec(n);
        vector<int64_t> b_vec(m);
        for (int64_t i = 0; i < n; ++i) cin >> a_vec[i];
        for (int64_t i = 0; i < m; ++i) cin >> b_vec[i];

        vector<int64_t> accumulate_a(n + 1);
        for (int64_t i = 1; i < n + 1; ++i)
            accumulate_a[i] = accumulate_a[i - 1] + a_vec[i-1];
        vector<int64_t> accumulate_b(m + 1);
        for (int64_t i = 1; i < m + 1; ++i)
            accumulate_b[i] = accumulate_b[i - 1] + b_vec[i-1];
        int64_t ans = 0;
        for (int64_t i = 0; i < n + 1; ++i) {
            if (k - accumulate_a[i] < 0) break;
            int64_t tmp = i + distance(accumulate_b.begin(),
                                       upper_bound(accumulate_b.begin(),
                                                   accumulate_b.end(),
                                                   k - accumulate_a[i]));
            ans = max(ans, tmp);
        }
        for (int64_t i = 0; i < m + 1; ++i) {
            if (k - accumulate_b[i] < 0) break;
            int64_t tmp = i + distance(accumulate_a.begin(),
                                       upper_bound(accumulate_a.begin(),
                                                   accumulate_a.end(),
                                                   k - accumulate_b[i]));
            ans = max(ans, tmp);
        }

        cout << max(int64_t(0), ans-1) << endl;

    }
};


int main() {
    CTsundoku solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
