#include <bits/stdc++.h>
#define rep(i,n) for(int (i)=0;(i)<(n);(i)++)
#define ALL(v) v.begin(), v.end()
#define INF 1e9

typedef long long ll;

using namespace std;


void solve(long long N, long long A, long long B, long long C, long long D, long long E){
    vector<ll> ABCDE = {A, B, C, D, E};
    ll m = *min_element(ALL(ABCDE));
    ll ans = (N+m-1)/m+4;
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long C;
    scanf("%lld",&C);
    long long D;
    scanf("%lld",&D);
    long long E;
    scanf("%lld",&E);
    solve(N, A, B, C, D, E);
    return 0;
}
