#include <bits/stdc++.h>
using namespace std;


void solve(std::string S){
    int ret = 0;
    if(S=="SUN") ret = 7;
    if(S=="MON") ret = 6;
    if(S=="TUE") ret = 5;
    if(S=="WED") ret = 4;
    if(S=="THU") ret = 3;
    if(S=="FRI") ret = 2;
    if(S=="SAT") ret = 1;

    cout << ret << endl;

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
