/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: alireza_kaviani
 * Time: 2020-05-25 16:26:52
**/
#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update>;

typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<int, int> pii;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define SZ(x)                       ll(x.size())

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 1e6 + 10;
const ll LOG = 22;
const ll INF = 8e18;
const ll MOD = 1e9 + 7; // 998244353; // 1e9 + 9;

ll n , m , cost , ans = INF , A[MAXN] , ps[MAXN];
vector<pii> vec;

int main() {
    ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);

    cin >> n >> m;
    for(int i = 1 ; i <= n ; i++)   cin >> A[i];
    for(int i = 1 ; i + 1 <= n ; i++){
        cost += (A[i + 1] - A[i] + m) % m;
        int L = A[i] + 1 , R = A[i + 1];
        if(A[i] == A[i + 1])    continue;
        if(L > R)   R += m;
        ps[L + 1]++; ps[R + 1]--;
        vec.push_back({R + 1 , R - L});
    }
    partial_sum(ps , ps + MAXN , ps);
    for(pii i : vec)    ps[i.X] -= i.Y;
    partial_sum(ps , ps + MAXN , ps);
    //for(int i = 1 ; i <= m + m ; i++) cout << ps[i] << sep;
    for(int i = 1 ; i <= m ; i++)   ans = min(ans , cost - ps[i] - ps[i + m]);
    cout << ans << endl;

    return 0;
}
/*

*/
