/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: alireza_kaviani
 * Time: 2020-05-19 21:38:36
**/
#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update>;

typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<int, int> pii;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define SZ(x)                       ll(x.size())

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 1e5 + 10;
const ll LOG = 22;
const ll INF = 8e18;
const ll MOD = 1e9 + 7; // 998244353; // 1e9 + 9;

int n , m , cnt , fen[MAXN] , ans[MAXN];
vector<pii> Q[MAXN];

void add(int x , int val){
    for( ; x < MAXN ; x += x & -x)  fen[x] += val;
}

int get(int x){
    int ans = 0;
    for( ; x > 0 ; x -= x & -x) ans += fen[x];
    return ans;
}

int main() {
    ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);

    cin >> n >> m;
    for(int i = 0 , l , r ; i < n ; i++){
        cin >> l >> r;
        Q[r - l + 1].push_back({l , r});
    }

    for(int i = 1 ; i <= m ; i++){
        for(pii j : Q[i])   add(j.X , 1) , add(j.Y + 1 , -1) , cnt++;
        for(int j = i ; j <= m ; j += i)    ans[i] += get(j);
        ans[i] += n - cnt;
    }
    for(int i = 1 ; i <= m ; i++)   cout << ans[i] << endl;

    return 0;
}
/*

*/
