#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <algorithm>
#include <queue>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <new>

#define REP(i,n) for(ll i=0;i<(ll)(n);i++)
#define REPD(i,n) for(ll i=n-1;i>=0;i--)
#define FOR(i,a,b) for(ll i=a;i<=(ll)(b);i++)
#define FORD(i,a,b) for(ll i=a;i>=(ll)(b);i--)
typedef long long ll;
using namespace std;

// 桁数を数える
int digit_length( int num )
{
    int count = 0;
    while( num ) {
        num = num / 10;
        ++count;
    }
    return count;
}

// 各桁を配列要素に分解 その先頭ポインタを返す
int* slice_digit( int num )
{
    int mod = 0;
    int *parts = NULL;

    try {
        parts = new int[ digit_length( num ) ];
    }
    catch( bad_alloc ba ) {
        exit(EXIT_FAILURE);
    }
    catch(...) {
        cout << "something went wrong\n";
    }

    int i = 0;
    while( num >= 1 )   {
        mod = num % 10; // 一の位の余り
        num = num / 10; // 取得済みの余りを"num"から除去
        parts[i++] = mod;
    }
    return parts;
}


void solve(long long N){
    // ここをユーザスニペットにしていく
    vector<vector<int> > c(9+1, vector<int>(9+1));
    REP(i, 9+1) REP(j, 9+1) c[i][j] = 0;


    FOR(i, 1, N) {
        // 数値を文字列に変換する
        string str = to_string(i);
        // cout << str[i] < <endl;
        int* digits = slice_digit(i);
        int d_len = digit_length(i);
        int idx_i = digits[0];
        int idx_j = digits[d_len-1];
        c[idx_i][idx_j]++;
    }

    long long res = 0;
    FOR(i, 1, 9) {
        FOR(j, 1, 9) {
            res += c[i][j] * c[j][i];
        }
    }
    cout << res  << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
