/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author TM
 */


#include <bits/stdc++.h>

#define MOD 1e9+7

using namespace std;

class DHandstand2 {
public:
  static void solve(std::istream &cin, std::ostream &cout) {
    int n;
    cin >> n;
    int64_t ans = 0;
    map<pair<int64_t, int64_t>, int64_t> m;
    for (int num = 1; num < n + 1; ++num) {
      string s = to_string(num);
      auto p = make_pair(s.front(), s.back());
      m[p]++;
    }
    for (int i = 0; i < n + 1; ++i) {
      string s = to_string(i);
      auto p = make_pair(s.front(), s.back());
      ans += m[make_pair(p.second, p.first)];
    }
    cout << ans << endl;
  }
};


int main() {
  DHandstand2 solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
