#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG

void solve(long long N, std::vector<long long> A){
    // 可能かどうかだけさきにみる
    ll current = -1;
    for(auto iter: A){
        if(iter <= current + 1){
            // ok
        }else{
            // 不可能
            cout << -1 << endl;
            return;
        }
        current = iter;
    }

    // 個数をもとめる
    ll res = 0;
    for(int i=0; i < A.size() - 1; i++){
        if(A.at(i) < A.at(i+1)){
            // 増加してるならよいい
        }else{
            // iが増加しているところのうち末尾
            res += A.at(i);
        }
    }
    res += A.back();

    cout << res << endl;

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
