/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long


class BRingosFavoriteNumbers {
public:
    int mpow(const int &a, int n) noexcept {
      if (n == 0) return 1;
      auto t = mpow(a, n / 2);
      t = t * t;
      if (n & 1) t = t * a;
      return t;
    }

    void solve(std::istream &in, std::ostream &out) {
      int d, n;
      in >> d >> n;
      out << (n == 100 ? mpow(100, d) * n + mpow(100, d) : mpow(100, d) * n) << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BRingosFavoriteNumbers solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
