/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long


class AProgrammingEducation {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      in >> n;
      int a, b;
      if (n == 2) {
        in >> a >> b;
        out << a + b << endl;
      } else {
        out << "Hello World" << endl;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AProgrammingEducation solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
