#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> a, long long sum){
  long long mymin = LLONG_MAX;
  long long minidx;

  for(long long i = 0; i < N; i++){
    if(mymin > abs(sum - a[i]*N)) {
      mymin = min(mymin, abs(sum - a[i]*N));
      minidx = i;
    }
  }

  cout << minidx << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N, sum = 0;
  scanf("%lld",&N);
  std::vector<long long> a(N-1-0+1);
  for(int i = 0 ; i < N-1-0+1 ; i++){
    scanf("%lld",&a[i]);
    sum += a[i];
  }
    solve(N, std::move(a), sum);
    return 0;
}
