/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
typedef pair<int, int> P;


class BTimeLimitExceeded {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n, t;
      in >> n >> t;
      vector<P> ct(n);
      REP(i, n) {
        int x, y;
        in >> x >> y;
        ct[i] = P(x, y);
      }
      sort(ct.begin(), ct.end(), [](P a, P b) {
          return a.first < b.first;
      });
      REP(i, n) {
        if (ct[i].second <= t) {
          out << ct[i].first << endl;
          return;
        }
      }
      out << "TLE" << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BTimeLimitExceeded solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
