#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long T, std::vector<long long> c, std::vector<long long> t){
  long long mymin = LLONG_MAX;

  for(long long i = 0; i < N; i++){
    if(mymin > c[i] && T >= t[i]) {
      mymin = c[i];
    }
  }

  if( mymin == LLONG_MAX){
    cout << "TLE" << endl;
  }
  else {
    cout << mymin << endl;
  }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  long long T;
  scanf("%lld",&T);
  std::vector<long long> c(N);
  std::vector<long long> t(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&c[i]);
    scanf("%lld",&t[i]);
  }
    solve(N, T, std::move(c), std::move(t));
    return 0;
}
