#include <bits/stdc++.h>
using namespace std;

#include <atcoder/fenwicktree>
using namespace atcoder;

void solve(int N, int Q, vector<int> a, vector<int> t, vector<int> l, vector<int> r) {
    fenwick_tree<long long> fw(N);
    for (int i = 0; i < N; i++) {
        fw.add(i, a[i]);
    }
    for (int i = 0; i < Q; i++) {
        if (t[i] == 0) {
            fw.add(l[i], r[i]);
        } else {
            cout << fw.sum(l[i], r[i]) << endl;
        }
    }
}


// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    // Failed to predict input format
    int N, Q;
    cin >> N >> Q;
    vector<int> a(N);
    for (int i = 0; i < N; i++) {
        cin >> a[i];
    }
    vector<int> t(Q), l(Q), r(Q);
    for (int i = 0; i < Q; i++) {
        cin >> t[i] >> l[i] >> r[i];
    }
    solve(N, Q, a, t, l, r);
    return 0;
}
