#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

const string YES = "Yes";
const string NO = "No";

void solve(long long N, long long x){
    const ll M = 2 * N - 1;
    if(x == 1 || x == M){
        cout << NO << endl;
        return;
    }

    x--;
    vector<ll> ans(M, -1);
    set<ll> rest;
    REP(i, M){ rest.insert(i); }
    ans.at(M / 2) = x;
    rest.erase(x);
    ans.at(M / 2 + 1) = x + 1;
    rest.erase(x + 1);
    ans.at(M / 2 - 1) = x - 1;
    rest.erase(x - 1);
    if(M > 3){
        if(x - 2 >= 0){
            ans.at(M / 2 + 2) = x - 2;
            rest.erase(x - 2);
        }else{
            ans.at(M / 2 - 2) = x + 2;
            rest.erase(x + 2);
        }
    }
    REP(i, M){
        if(ans.at(i) == -1){
            ans.at(i) = *rest.begin();
            rest.erase(rest.begin());
        }
    }

    cout << YES << endl;
    REP(i, M){
        cout << ans.at(i) + 1 << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    long long x;
    scanf("%lld",&x);
    solve(N, x);
    return 0;
}
