#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::string A, std::string B, std::string C){
  long long count = 0;
  for(long long i = 0; i < N; i++) {
    vector<long long> tab({A[i], B[i], C[i]});
    sort(tab.begin(), tab.end());

    tab.erase(unique(tab.begin(), tab.end()), tab.end());
    count += (tab.size()-1);
  }

  cout << count << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::string A;
  std::cin >> A;
  std::string B;
  std::cin >> B;
  std::string C;
  std::cin >> C;
    solve(N, A, B, C);
    return 0;
}
