/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class BBitterAlchemy {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n, x;
      in >> n >> x;
      vector<int> m(n);
      REP(i, n) in >> m[i];
      int sum = accumulate(m.begin(), m.end(), 0ll);
      int minm = *min_element(m.begin(), m.end());
      int left = x - sum;
      out << n + left / minm << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BBitterAlchemy solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
