#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long X, std::vector<long long> m){

  cout << (N + ((X-accumulate(m.begin(), m.end(), 0ll))/(*min_element(m.begin(), m.end())))) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  long long X;
  scanf("%lld",&X);
  std::vector<long long> m(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&m[i]);
  }
    solve(N, X, std::move(m));
    return 0;
}
