#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A, std::vector<long long> B, std::vector<long long> C){
  long long prev = A[0];
  long long acc = B[A[0]-1];

  for(long long i = 1; i < N; i++) {
    acc += B[A[i]-1];

    if(prev + 1 == A[i]) acc+= C[prev-1];
    prev = A[i];
  }

  cout << acc << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> A(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&A[i]);
  }
  std::vector<long long> B(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&B[i]);
  }
  std::vector<long long> C(N-1);
  for(int i = 0 ; i < N-1 ; i++){
    scanf("%lld",&C[i]);
  }
    solve(N, std::move(A), std::move(B), std::move(C));
    return 0;
}
