#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A, std::vector<long long> accs){
  long long mymin = LLONG_MAX;
  long long acc = 0;
  for(long long i = (N-2); i >= 0; i--){
    acc += A[i+1];

    mymin = min(mymin, abs(accs[i] - acc));
  }

  cout << mymin << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    long long acc = 0;
  scanf("%lld",&N);
  std::vector<long long> A(N);
  std::vector<long long> accs(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&A[i]);
    acc += A[i];
    accs[i] = acc;
  }
    solve(N, std::move(A), move(accs));
    return 0;
}
