#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A){
    // i番目で区切って、前後の差が最小のところを探す
    int sum = 0;
    if(A.size() == 2){
        cout << abs(A[0] - A[1]) << endl;
        return;
    }
    vector<long long> B(A.size());
    B[0] = A[0];
    for(int i =1; i < B.size(); i++){
        B[i] = B[i-1] + A[i];
    }
    long long ans = B[B.size()-1];
    for(int i = 1; i < B.size()-1; i++){
        long long diff = abs( B[i] -  (B[B.size()-1] - B[i]));
        if(diff < ans){
            ans = diff;
        }
    }

    cout << ans << endl;


}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
