/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(int i = 0; i < (int)(n); i++)
#define all(v) v.begin(), v.end()

class BProblemSet {
public:
	void solve(std::istream& in, std::ostream& out) {
	    ll n;
	    in>>n;
	    map<ll,ll> d;
	    rep(i,n){
	        ll tmp;
	        in>>tmp;
	        d[tmp]++;

	    }
	    ll m;
	    in>>m;
	    map<ll,ll> t;
	    rep(i,m){
	        ll tmp;
	        in>>tmp;
	        t[tmp]++;
	    }
        bool ans=true;
	    for(const auto &i: t){

	        if(i.second>d[i.first]) ans=false;
	    }
	    if(ans) out<<"YES"<<endl;
	    else out<<"NO"<<endl;


	}
};


int main() {
	BProblemSet solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
