#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(long long N, std::vector<long long> D, long long M, std::vector<long long> T){
  map<long long, long long> countD;
  map<long long, long long> countT;

  for(long long i = 0; i < N; i++) {
    countD[D[i]]++;
  }

  for(long long i = 0; i < M; i++) {
    countT[T[i]]++;
  }


  for(long long i = 0; i < M; i++) {
    long long now = T[i];
    if(countD[now] < countT[now]) {
      cout << NO << endl;
      return;
    }
  }

  cout << YES << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> D(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&D[i]);
  }
  long long M;
  scanf("%lld",&M);
  std::vector<long long> T(M);
  for(int i = 0 ; i < M ; i++){
    scanf("%lld",&T[i]);
  }
    solve(N, std::move(D), M, std::move(T));
    return 0;
}
