#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;
const long long MOD = 1000000007;

void solve(long long N, std::vector<long long> C){
  
    vector<ll> D;
    for(int i=0;i<N;i++){
        if(i<N-1&& C[i] == C[i+1]){
            continue;
        }
        D.push_back(C[i]);
    }
    ll size = D.size();
    map<ll,ll> mp;
    vector<ll> dp(size+1);
    dp[0] =1;
    for(int i=0;i<size;i++){
        if(mp.find(D[i]) == mp.end()){
            dp[i+1] = dp[i];
            mp[D[i]] = i;
            continue;
        }
        int t= mp[D[i]];
        dp[i+1] = dp[i] + dp[t+1];
        dp[i+1] %= MOD; 
        mp[D[i]] =i;
    }
    // mp.clear();
    // vector<ll> rdp(size+1);
    // rdp[size] =1;
    // for(int i=size-1;i>=0;--i){
    //     if(mp.find(D[i]) == mp.end()){
    //         rdp[i] = rdp[i+1];
    //         mp[D[i]] =i;
    //         continue;
    //     }
    //     int t= mp[D[i]];
    //     rdp[i] = rdp[i+1] + rdp[t];
    //     rdp[i] %= MOD;
    //     mp[D[i]] =i;
    // }
    cout << dp[size] << endl;
    return;
    // ll ans =1;
    // for(int i=0;i<size;i++){
    //     cerr <<"dp=" << dp[i+1] <<"rdp=" << rdp[i+1] << endl;
    //     ans = (ans + dp[i+1]*rdp[i+1] -1 + MOD) % MOD;
    // }
    // cout << ans << endl;


}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> C(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&C[i]);
    }
    solve(N, std::move(C));
    return 0;
}
