#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A, std::vector<long long> B){
  long long mymax = B[0];
  long long maxpos = A[0];
  for(long long i = 1; i < N; i++){
    if(mymax > B[i]) {
      mymax = B[i];
      maxpos = A[i];
    }
  }

  cout << (mymax+maxpos) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> A(N);
  std::vector<long long> B(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&A[i]);
    scanf("%lld",&B[i]);
  }
    solve(N, std::move(A), std::move(B));
    return 0;
}
