/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
#define ITR(itr, mp) for(auto itr = (mp).begin(); itr != (mp).end(); ++itr)


class BMaximumSum {
public:
    void solve(std::istream &in, std::ostream &out) {
      multiset<int, greater<int>> m;
      int a, b, c, k;
      in >> a >> b >> c >> k;
      m.insert(a);
      m.insert(b);
      m.insert(c);
      REP(i, k) {
        int t = *m.begin();
        m.erase(m.begin());
        t *= 2;
        m.insert(t);
      }
      int ans = 0;
      ITR(itr, m) {
        ans += *itr;
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BMaximumSum solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
