#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long C, long long K){
  long long mymax = max(A, max(B, C));
  long long acc = A + B + C;

  cout << ((acc - mymax) + mymax * pow(2, K)) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long C;
  scanf("%lld",&C);
  long long K;
  scanf("%lld",&K);
    solve(A, B, C, K);
    return 0;
}
