/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <bits/stdc++.h>
#define REP(i, n) for(int i=0;i<(n);++i)
#define RREP(i, n) for(int i=1;i<=(n);++i)
#define ALL(v) (v).begin(), (v).end()
#define RALL(v) (v).rbegin(), (v).rend()
#define DUMP(x) cout<<#x<<"="<<(x)<<endl;
#define pb push_back
#define eb emplace_back
using namespace std;
typedef long long lint;
typedef pair<int, int> pii;
typedef pair<lint, lint> pll;

class BTournament {
public:
    int N;
    vector<vector<int>> G;

    void input(std::istream& in){
        ios_base::sync_with_stdio(false);
        in>>N;
        G = vector<vector<int>>(N, vector<int>());
        RREP(i, N-1){
            int a;
            in>>a;
            a--;
            G[i].pb(a), G[a].pb(i);
        }
    }

    int dfs(int s, int p){
        vector<int> vec;
        for(auto u : G[s]){
            if(u==p) continue;
            vec.pb(dfs(u, s));
        }
        sort(RALL(vec));
        int res = 0, mx = 0;
        RREP(i, vec.size()){
            if(i+vec[i-1]>mx){
                res += i + vec[i-1] - mx;
                mx = i + vec[i-1];
            }
        }
        return res;
    }

	void solve(std::istream& in, std::ostream& out) {
        input(in);
        out<<dfs(0, -1)<<'\n';
	}
};


int main() {
	BTournament solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
