/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include<bits/stdc++.h>
using namespace std ;

using ll = long long ;

class BCardGameForTwo {
public:
	void solve(std::istream& cin, std::ostream& cout) {
	    int n ;
	    cin >> n ;
	    vector<int> a(n) ;
	    for(int i = 0 ; i < n ; ++i){
	        cin >> a[i];
	    }
	    sort(a.rbegin() , a.rend());
	    int ans = 0 ;
	    for(int i = 0 ; i < n ; ++i){
	        if(i % 2 == 0){
	            ans += a[i] ;
	        }else{
	            ans -= a[i] ;
	        }
	    }
	    cout << ans ;

	}
};


int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
	BCardGameForTwo solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
