#include<bits/stdc++.h>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
using ll = long long;
const int inf=1e9+7;
const ll INF=1LL<<60 ;
const ll MOD=1e9+7 ;
template<class T> inline bool chmin(T& a, T b) { if (a > b) { a = b; return true; } return false; }
template<class T> inline bool chmax(T& a, T b) { if (a < b) { a = b; return true; } return false; }


// Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
const int nmax = 500;
int edge[nmax][nmax];
void dfs(int indent_plus, int now_points, int tukatteiiLevel)
{
    if (now_points==1) return;
    rep(i,now_points/2)
    {
        rep(j,now_points/2+(now_points%2))
        {
            int x = indent_plus + i;
            int y = indent_plus + j + now_points/2;
            edge[x][y] = edge[y][x] = tukatteiiLevel;
        }
    }
    dfs(indent_plus, now_points/2, tukatteiiLevel+1);
    dfs(indent_plus+now_points/2, now_points/2 + (now_points%2), tukatteiiLevel+1);
    return;
}

int main(){
    int n;
    cin >> n;

    rep(i,n) rep(j,n) edge[i][j] = 0;
    dfs(0, n, 1);
    rep(i,n)
    {
        REP(j,i+1,n)
        {
            cout << edge[i][j];
            if (j!=n-1) cout << " ";
        }
        cout << endl;
    }
}
