#include <bits/stdc++.h>
using namespace std;


void solve(long long N){
    vector<vector<int>> res(N, vector<int>(N,-1));
    int k=2;
    for(int t=0;t<11;++t){
        for(int i=0;i<N;++i){
            for(int j=i+1;j<N;++j){
                if((i>>t)%2!=(j>>t)%2){
                    if(res[i][j]==-1)res[i][j]=t+1;
                }
            }
        }
    }
    for(int i=0;i<N-1;++i){
        for(int j=i+1;j<N-1;++j){
            cout<<res[i][j]<<" ";
        }
        cout<<res[i][N-1]<<endl;
    }
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
