/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class CAttackSurvival {
public:
    void solve(istream& cin, ostream& cout) {
        ll n, k , q;
        cin >> n >> k  >> q;
        vector<int> cor(n+1, 0);
        for(int i=0; i<q; i++) {
            int tp;
            cin >> tp;
            cor[tp]++;
        }
        for(int i=1; i<=n; i++) {
            cor[i] = cor[i] - q + k;
            cout << ((cor[i] > 0) ? "Yes\n": "No\n");
        }
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    CAttackSurvival solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
