#include <bits/stdc++.h>
using namespace std;


void solve(std::string s){
    int rockCount = 0;
    int paperCount = 0;
    for (auto ch : s) {
      if (ch == 'g') {
	  rockCount++;
      } else {
	  paperCount++;
      }
    }
    int maxPaper = s.size()/2;
    cout << maxPaper - paperCount << endl;
}

// Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string s;
    std::cin >> s;
    solve(s);
    return 0;
}
