#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(long long A, long long V, long long B, long long W, long long T)
{
    if (V <= W || abs(B - A) > (V - W) * T)
        cout << NO << endl;
    else
        cout << YES << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long V;
    scanf("%lld", &V);
    long long B;
    scanf("%lld", &B);
    long long W;
    scanf("%lld", &W);
    long long T;
    scanf("%lld", &T);
    solve(A, V, B, W, T);
    return 0;
}
