#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long C){
  long long ab = A*B;
  long long bc = B*C;
  long long ac = A*C;

  if(A % 2 == 0 || B % 2 == 0 || C % 2 == 0) {
    cout << 0 << endl;
    return;
  }

  vector<long long> vec({ab, bc, ac});
  cout << *min_element(vec.begin(), vec.end()) << endl;
  return;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long C;
  scanf("%lld",&C);
    solve(A, B, C);
    return 0;
}
