#include <bits/stdc++.h>
#define rep(i, n) for (int i = 0; i < (int)(n); i++)

using namespace std;




void solve(long long N, std::vector<long long> a){
    vector<long long > sleft(N+1), sright(N+1);
    priority_queue<long long, vector<long long>, greater<int> > pqleft;
    priority_queue<long long> pqright;
    long long tmp, maxscore=LLONG_MIN;
    //* initilization
    rep(i, N){
        sleft[0] += a[i];
        pqleft.push(a[i]);
        sright[N] += a[i+2*N];
        pqright.push(a[i+2*N]);
    }
    //* update left part
    rep(i, N){
        pqleft.push(a[i+N]);
        tmp = pqleft.top();
        pqleft.pop();
        sleft[i+1] = sleft[i] + a[i+N] - tmp;
    }
    //* update right part
    rep(i, N){
        pqright.push(a[2*N-i-1]);
        tmp = pqright.top();
        pqright.pop();
        sright[N-i-1] = sright[N-i] + a[2*N-i-1] - tmp;
    }
    //* get max score
    rep(i, N+1){
        maxscore = max(maxscore, sleft[i] - sright[i]);
    }
    cout << maxscore << endl;

}

// Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> a(3*N);
    for(int i = 0 ; i < 3*N ; i++){
        scanf("%lld",&a[i]);
    }
    solve(N, std::move(a));
    return 0;
}
