/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (win, macOS, linux)
 * Author: ashiknur
 * Time: 2020-02-27 23:40:08
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;

int main()
{
    ios::sync_with_stdio(false);
    cin.tie(0);
    int count=0,sum=0,flag=0;
    string s;
    cin>>s;
    for(int i=0;i<s.size();i++)
    {
       if( s[i]=='h')
       {
           count++;
       }
       else if(s[i]=='i')
       {
           sum++;
       }
    }
   for(int i=0;i<s.size()-1;i++)
   {
       if(s[i]=='h' && s[i+1]=='i')
       {
           flag++;
       }
   }
   if(flag==(count+sum+1)/2 && count+sum==s.size())
   {
       cout<<"Yes"<<endl;
       return 0;
   }
   cout<<"No"<<endl;

}

