#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<std::vector<long long>> A)
{
    long long S = 0;
    long long maxa = 0;
    long long up = 0;

    for (int i = 0; i < N; i++)
    {
        up += A[0][i];
        maxa = up;
    }

    for (int i = 0; i < N - 1; i++)
    {
        S += A[0][i];
        long long down = 0;
        down += S; //こいつの位置がおかしかった。
        for (int j = i; j < N - 1; j++)
        {
            down += A[1][j];
        }
        maxa = max(maxa, down);
    }
    maxa += A[1][N - 1];
    cout << maxa << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<std::vector<long long>> A(2, std::vector<long long>(N));
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < N; j++)
        {
            scanf("%lld", &A[i][j]);
        }
    }
    solve(N, std::move(A));
    return 0;
}
