/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long


class A753 {
public:
    void solve(std::istream &in, std::ostream &out) {
      int x;
      in >> x;
      switch (x) {
        case 7:
        case 5:
        case 3:
          out << "YES" << endl;
          break;
        default:
          out << "NO" << endl;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  A753 solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
