#include <bits/stdc++.h>
using namespace std;
using ll = long long;
const ll INF = ll(1e18)+5;


void solve(long long N, long long K, std::vector<long long> A, std::vector<long long> F){
    sort(A.begin(),A.end());
    sort(F.rbegin(),F.rend());
    ll l=-1;
    ll r = INF;
    while(l+1<r){
        ll mid = (l+r)/2;
        ll sum =0;
        for(int i=0;i<N;i++){
            sum += max(0ll, A[i]-(mid/F[i]));
        }
        if(sum>K){
            l  =mid;
        }else{
            r = mid;
        }
    }
    cout << r << endl;


}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    std::vector<long long> F(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&F[i]);
    }
    solve(N, K, std::move(A), std::move(F));
    return 0;
}
