#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG


bool isOk(long long N, long long K, std::vector<long long> A, std::vector<long long> F, ll val){
    ll ops = 0;
    for(int i=0; i < N; i++){
        // A.at(i)*F.at(i) <= valとなるようA.at(i)を調整する必要がある。
        // つまり、A.at(i) <= val/F.at(i)となるようにする必要があり、
        // A.at(i) > val/F.at(i) のときにはval/F.at(i)-A.at(i)だけ左辺にたしてそうする。opsもたす
        if(A.at(i) > val/F.at(i)){
            ops += abs(val/F.at(i) - A.at(i));
        }
    }

    return ops <= K;
}

void solve(long long N, long long K, std::vector<long long> A, std::vector<long long> F){
    sort(A.begin(), A.end());
    auto cmp = [](ll a, ll b){return a > b;};
    sort(F.begin(), F.end(), cmp);

    ll inf = 0;
    for(int i=0; i < N; i++){
        inf = max(inf, A.at(i)*F.at(i));
    }

    ll ng = -1;
    ll ok = inf + 1;
    while(abs(ok - ng) > 1){
        ll piv = (ok + ng)/2;
        if(isOk(N, K, A, F, piv)){
            ok = piv;
        }else{
            ng = piv;
        }

    }

    cout << ok << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    std::vector<long long> F(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&F[i]);
    }
    solve(N, K, std::move(A), std::move(F));
    return 0;
}
