/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author ayuame
 */

#include <bits/stdc++.h>
#pragma GCC optimize("Ofast")

#define REP(i, n) for (int i = 0; i < n; i++)
#define FOR(i, m, n) for (int i = m; i < n; i++)
#define ALL(v) v.begin(), v.end()

using namespace std;
typedef pair<int, int> P;
typedef long long ll;

class ANumberOfMultiples {
public:
	void solve(std::istream& cin, std::ostream& cout) {
	  int L, R, d, cnt = 0;
	  cin >> L >> R >> d;
	  FOR(i, L, R+1) {
	    if (i % d == 0) {
	      cnt++;
	    }
	  }
	  cout << cnt << endl;
	}
};

int main() {
	ANumberOfMultiples solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}