#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;
const long long MOD = 2;

void solve(long long N, std::vector<long long> a){
    vector<ll> ans;
    vector<int> hasBall(N,0);
    for(int i=N-1;i>=0;--i){
        ll num = i+1;
        ll t =2;
        ll sum =a[i];
        while(num*t<=N){
            sum += hasBall[num*t-1];
            ++t;
        }
        if(sum%2==1){
            hasBall[i] =1;
            ans.push_back(num);
        }
    }
    cout << ans.size() <<endl;
    sort(ans.begin(),ans.end());
    for(ll num:ans){
        cout << num << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> a(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&a[i]);
    }
    solve(N, std::move(a));
    return 0;
}
