#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long K, std::vector<long long> D){
    while(1) {
        bool isFind = false;
        for (auto i=D.begin(); i!=D.end(); i++) {
            string N_str = to_string(N);
            string i_str = to_string(*i);
            if (N_str.find(i_str.c_str()) != string::npos) {
                isFind = true;
                break;
            }
        }
        if (isFind == false) {
            cout << to_string(N) << endl;
            break;
        }
        N++;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> D(K);
    for(int i = 0 ; i < K ; i++){
        scanf("%lld",&D[i]);
    }
    solve(N, K, std::move(D));
    return 0;
}
