#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(long long N, long long M, long long C, vector<long long> B,
           vector<vector<long long>> A) {
    ll ans = 0;
    FOR(i, 0, N-1) {
        int sum = 0;
        rep(m, M) {
            sum += A[i][m] * B[m];
        }
        sum += C;

        if (sum > 0) {
            ans++;
        }
    }

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  cin >> N;
  long long M;
  cin >> M;
  long long C;
  cin >> C;
  vector<long long> B(M);
  for (int i = 0; i < M; i++) {
    cin >> B[i];
  }
  vector<vector<long long>> A(N, vector<long long>(M));
  for (int i = 0; i < N; i++) {
    for (int j = 0; j < M; j++) {
      cin >> A[i][j];
    }
  }
  solve(N, M, C, move(B), move(A));
  return 0;
}
