#include <bits/stdc++.h>
using namespace std;

void solve(long long sx, long long sy, long long tx, long long ty) {
    string S = "";
    long long dy = abs(ty - sy), dx = abs(tx - sx);
    S += string(dy, 'U') + string(dx, 'R') + string(dy, 'D') + string(dx, 'L') + 'L' + string(dy + 1, 'U') +
         string(dx + 1, 'R') + 'D' + 'R' + string(dy + 1, 'D') + string(dx + 1, 'L') + 'U';
    cout << S << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
    long long sx;
    scanf("%lld", &sx);
    long long sy;
    scanf("%lld", &sy);
    long long tx;
    scanf("%lld", &tx);
    long long ty;
    scanf("%lld", &ty);
    solve(sx, sy, tx, ty);
    return 0;
}
