/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define se cout << "test ok" << endl;
#define sp << " " <<
#define enl "\n";
using namespace std;
using ll=long long;
using ld=long double;
ll mod = ll(1e9)+7;
ll inf = ll(1e18);
template<typename T1, typename T2> ll ceill(T1 a, T2 b){ return (a+b-1)/b; }
void ans(bool b, ostream& out=cout){ out << (b ? "Yes" : "No") << endl; }
void ans2(bool b, ostream& out=cout){ out << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b){a=b; return true;} return false; }
template<typename T> inline bool chmin(T &a, T b){ if(a>b){a=b; return true;} return false; }
template<typename A, size_t N, typename T> void Fill(A (&array)[N], const T &val){ fill((T*)array, (T*)(array+N), val); }
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};

#ifndef INCLUDE_DEBUG_HPP
#define INCLUDE_DEBUG_HPP

#include <iostream>
#include <vector>
#include <map>
using namespace std;

namespace dbg {
    using ll = long long;

    class Debug {
    public:
        Debug(){}
        template<typename T>
        void vd(vector<T> vec);
        template<typename T>
        void vd2(vector<vector<T>> vec);
        template<typename T>
        void ad(T *arr, ll n);
        template<typename T, size_t N>
        void ad2(T (&arr)[N], ll n);
        template<typename T>
        void md(T mp);
    };

    template<typename T>
    void Debug::vd(vector<T> vec) {
        for (auto vv : vec) cout << vv << " ";
        cout << endl;
    }

    template<typename T>
    void Debug::vd2(vector<vector<T>> vec) {
        for (auto vv : vec) for (auto vvv : vv) cout << vvv << " ";
        cout << endl;
    }

    template<typename T>
    void Debug::ad(T *arr, ll n) {
        for (int i = 0; i <= n; i++) cout << arr[i] << " ";
        cout << endl;
    }

    template<typename T, size_t N>
    void Debug::ad2(T (&arr)[N], ll n) {
        for (int i = 0; i <= N; i++) for (int j = 0; j <= n; j++) cout << arr[i][j] << " ";
        cout << endl;
    }

    template<typename T>
    void Debug::md(T mp) {
        cout << "key : value" << endl;
        for (auto const &m : mp) cout << m.first << " : " << m.second << endl;
        cout << endl;
    }

}

#endif //INCLUDE_DEBUG_HPP

using dbg::Debug;
Debug debug;

class DGoodGrid {
public:
	void solve(std::istream& in, std::ostream& out) {
	    ll n, c;
	    in >> n >> c;
	    vector<vector<int>> d(c, vector<int>(c));
	    vector<vector<int>> g(n, vector<int>(n));
	    for(int i=0; i<c; i++){
	        for(int j=0; j<c; j++){
	            in >> d[i][j];
	        }
	    }
	    for(int i=0; i<n; i++){
	        for(int j=0; j<n; j++){
	            in >> g[i][j];
	            --g[i][j];
	        }
	    }

	    vector<vector<ll>> v(3, vector<ll>(c, 0));
	    for(int k=0; k<c; k++) {
            for (int i=0; i<n; i++) {
                for (int j=0; j<n; j++) {
                    v[(i+j)%3][k] += d[g[i][j]][k];
                }
            }
        }

	    ll res = inf;
	    for(int i=0; i<c; i++){
	        for(int j=0; j<c; j++){
	            for(int k=0; k<c; k++){
                    if(i==j || j==k || k == i) continue;
                    chmin(res, v[0][i] + v[1][j] + v[2][k]);
//                    cout << i sp j sp k << enl;
//                    cout << v[0][i] sp v[1][j] sp v[2][k] << enl;
//                    cout << v[0][i] + v[1][j] + v[2][k] << enl;
	            }
	        }
	    }

	    out << res << endl;
	}
};


int main() {
	DGoodGrid solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
