#include <bits/stdc++.h>
using namespace std;


void solve(std::string S){
    int sum =700;
    
    for(int i = 0;i<3;i++){
    if(S[i]=='o')
    {
        sum += 100;  
    }
    }
    cout << sum << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
