/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define RFOR(i, a, b) for(int i = (int)(b-1);i>=(int)(a);--i)
#define REP(i, n)  FOR(i,0,(n))
#define RREP(i, n) RFOR(i,0,(n))
typedef vector<int> vec;


class CAllGreen {
public:
    vector<int> ans;
    int g, d;
    vec p, c;

    void dfs(int v, vector<bool> f, int sum, int cnt) {
      if (sum >= g) {
        ans.push_back(cnt);
        return;
      }
      if (v == d) {
        RREP(i, f.size()) {
          REP(j, p[i]) {
            if (!f[i]) {
              cnt++;
              sum += 100 * (i + 1);
              if (sum >= g) {
                ans.push_back(cnt);
                return;
              }
            }
          }
          if (!f[i]) sum += c[i];
        }
        return;
      }
      //全完しない
      dfs(v + 1, f, sum, cnt);
      //全完する
      vector<bool> tf = f;
      tf[v] = true;
      dfs(v + 1, tf, sum + 100 * (v + 1) * p[v] + c[v], cnt + p[v]);

      return;
    }

    void solve(std::istream &in, std::ostream &out) {
      in >> d >> g;
      p = c = vec(d);
      REP(i, d) {
        in >> p[i] >> c[i];
      }
      vector<bool> f(d, false);
      dfs(0, f, 0, 0);
      int m = *min_element(ans.begin(), ans.end());
      out << m << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  CAllGreen solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
