#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG

const ll INF = 1123456789;

ll divUp(ll a, ll b){
    if(a%b == 0){
        return a/b;
    }
    return a/b + 1;
}

ll calc(ll D, ll G, vec<ll>& p, vec<ll>& c, int fullFlag){
    // fullFlagのものは先に全部つかってしまう。そうでないものは、利益のたかいものから順にp.at(i)-1個まで貪欲に使う。それでだめならINFをかえす。
    ll currentScore = 0;
    ll res = 0;
    // fullFlagのものは先に全部つかってしまう
    for(int i=0; i < D; i++){
        if ((fullFlag >> i) & 1){
            // i版はつかう
            currentScore += 100*(i+1)*p.at(i);
            // ボーナス
            currentScore += c.at(i);
            res += p.at(i);
        }
    }

    if(currentScore >= G){
        return res;
    }

    // 貪欲につかう
    for(int i=D-1; i >= 0; i--){
        // fullFlagがたってるならもうおわってるからいい。
        if((fullFlag >> i) & 1){
            continue;
        }
        ll useI = divUp(G - currentScore, 100*(i+1));
        // GのためにはuseI個だけ必要
        useI = min(p.at(i)  - 1, useI);
        // ある分しかつかえない。
        currentScore += useI*100*(i+1);
        res += useI;

        if(currentScore >= G){
            return res;
        }
    }

    return INF;
}

void solve(long long D, long long G, std::vector<long long> p, std::vector<long long> c){
    ll res = INF;
    for(int i=0; i < (1 << D); i++){
        res = min(res, calc(D, G, p, c, i));
    }
    cout << res << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long D;
    scanf("%lld",&D);
    long long G;
    scanf("%lld",&G);
    std::vector<long long> p(D);
    std::vector<long long> c(D);
    for(int i = 0 ; i < D ; i++){
        scanf("%lld",&p[i]);
        scanf("%lld",&c[i]);
    }
    solve(D, G, std::move(p), std::move(c));
    return 0;
}
