/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include<bits/stdc++.h>
using namespace std ;

using ll = long long ;

class ACookieExchanges {
public:
	void solve(std::istream& cin, std::ostream& cout) {
	    int a , b , c ;
	    cin >> a >> b >> c ;
	    int x = a  , y  = b , z = c ;
	    int ans = 0 ;
	    int ok = true ;
	    while(x % 2 == 0 && y % 2 == 0 && z % 2 == 0){
	        x = (a / 2) + (b / 2);
	        y =  (a / 2) + (c / 2) ;
	        z = (b / 2) + (c / 2) ;
	        if(a == x && b == y && c == z) {
	            ok = false ;
	            break ;
	        }
	        a = x ;
	        b = y ;
	        c = z ;

	        ans++ ;
	    }
	    if(ok){
	        cout << ans ;
	    }else{
	        cout << -1 ;
	    }

	}
};



int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
	ACookieExchanges solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
