/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <bitset>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(ll i = 0; i < (ll)(n); i++)
#define all(v) v.begin(), v.end()

class ACookieExchanges {
public:
	void solve(std::istream& in, std::ostream& out) {
        ll a,b,c;
        in>>a>>b>>c;
        if(a%2==0 && a==b && b==c && c==a){
            out<<-1<<endl;
            return;
        }
        ll cnt=0;
        while(a%2==0 && b%2==0 && c%2==0){
            ll aa,bb,cc;
            aa=a/2;
            bb=b/2;
            cc=c/2;
            a=bb+cc;
            b=aa+cc;
            c=aa+bb;
            ++cnt;
        }
        out<<cnt<<endl;
	}
};


int main() {
	ACookieExchanges solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
