//16:15~16:36
#include <bits/stdc++.h>
using namespace std;

int solve(long long &A, long long &B, long long &C)
{
    long long change = 0;
    long long A0, B0, C0;
    A0 = A;
    B0 = B;
    C0 = C;
    while (A0 % 2 == 0 && B0 % 2 == 0 && C0 % 2 == 0)
    {
        A = B0 / 2 + C0 / 2;
        B = A0 / 2 + C0 / 2;
        C = A0 / 2 + B0 / 2;
        A0 = A;
        B0 = B;
        C0 = C;
        change++;
        if (change == pow(10, 5))
        {
            cout << "-1" << endl;
            return 0;
        }
    }
    cout << change << endl;
    return 0;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    long long C;
    scanf("%lld", &C);
    solve(A, B, C);
    return 0;
}
