#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(long long A, long long B, long long C) {
    ll ans = 0;
    ll tmp_a, tmp_b, tmp_c;

    if (A == B && B == C && C == A && A%2 == 0) {
        ans = -1;
    } else {
        while (A%2 == 0 && B%2 == 0 && C%2 == 0) {
            tmp_a = B/2 + C/2;
            tmp_b = C/2 + A/2;
            tmp_c = A/2 + B/2;

            A = tmp_a;
            B = tmp_b;
            C = tmp_c;

            ans++;
        }
    }

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long A;
  cin >> A;
  long long B;
  cin >> B;
  long long C;
  cin >> C;
  solve(A, B, C);
  return 0;
}
