/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author rahdirigs
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

template <typename T> void add(T& a, T b, int mod) {
	a += b;
	if (a >= mod)
		a -= mod;
}

template <typename T> void sub(T& a, T b, int mod) {
	a -= b;
	if (a < 0)
		a += mod;
}

const int mod = 1e9 + 7;

class TaskT {
public:
	int N;
	string s;
	void solve(std::istream& in, std::ostream& out) {
		in >> N >> s;
		vector<vector<ll>> dp(N + 1, vector<ll> (N + 1, 0));
		dp[1][1] = 1;
		for (int i = 2; i <= N; i++) {
			vector<ll> pref(i, 0);
			pref[0] = dp[i - 1][0];
			for (int j = 1; j < i; j++) add(pref[j], pref[j - 1] + dp[i - 1][j], mod);
			for (int j = 1; j <= i; j++) {
				int l, r;
				if (s[i - 2] == '<')
					l = 1, r = j - 1;
				else
					l = j, r = i - 1;
				ll t = pref[r];
				sub(t, pref[l - 1], mod);
				dp[i][j] = t;
			}
		}
		ll ans = 0;
		for (int i = 1; i <= N; i++)
			add(ans, dp[N][i], mod);
		out << ans;
	}
};

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	TaskT solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
