#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, std::vector<long long> X, std::vector<long long> L)
{
    vector<pair<ll, ll>> robots;
    for (ll i = 0; i < N;i++) {
        robots.emplace_back(X[i] - L[i], X[i] + L[i]);
    }

    sort(begin(robots), end(robots), [](auto&& a, auto&& b) { return a.second < b.second; });

    ll ans = 1;
    ll s = robots[0].second;
    for (auto r : robots) {
        if (s <= r.first) {
            ans++;
            s = r.second;
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
#pragma GCC diagnostic ignored "-Wunused-result"
int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
    long long N;
    scanf("%lld",&N);
    std::vector<long long> X(N);
    std::vector<long long> L(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&X[i]);
        scanf("%lld",&L[i]);
    }
    solve(N, std::move(X), std::move(L));
    return 0;
}
