/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
typedef pair<int, int> P;


class BRobotArms {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      in >> n;
      vector<P> xl(n);
      REP(i, n) {
        int x, y;
        in >> x >> y;
        xl[i] = P(x, y);
      }
      sort(xl.begin(), xl.end(), [](P a, P b) {
          return a.first + a.second < b.first + b.second;
      });
      P t = xl[0];
      int ans = 1;
      FOR(i, 1, n) {
        if (t.first + t.second <= xl[i].first - xl[i].second) {
          ans++;
          t = xl[i];
        }
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BRobotArms solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
