/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class BKagamiMochi {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    set<int> d;
    REP(i,n) {
      int t;
      in >> t;
      d.insert(t);
    };
    out << d.size() << endl;

	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BKagamiMochi solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
