/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class BChristmasEveEve {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      in >> n;
      vector<int> p(n);
      REP(i, n) in >> p[i];
      int max_ele = *max_element(p.begin(), p.end());
      int t = max_ele / 2;
      int ans = 0;
      REP(i, n) {
        ans += p[i];
      }
      out << ans - t << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BChristmasEveEve solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
