#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;

void solve(long long N, long long K, std::string S){
    ll original = 0;
    for(int i=1;i<N;i++){
        if(S[i-1] == S[i]){
            original++;
        }
    }
    if(N==2){
        cout << original << endl;
        return;
    }
    cout << min(original + 2*K,N-1) << endl;

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::string S;
    std::cin >> S;
    solve(N, K, S);
    return 0;
}
