//ミス
#include <bits/stdc++.h>
using namespace std;

void solve(long long N)
{
    long double n2;
    long long A;
    if (N % 2 == 0)
        cout << 0.5000000000 << endl;
    else if (N % 2 == 1 && N != 1)
    {
        A = (N / 2) + 1;
        n2 = double(A) / double(N);
        cout << n2 << endl;
    }
    else
        cout << 1.0000000000 << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    solve(N);
    return 0;
}
