/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class BCoins {
public:
	void solve(std::istream& in, std::ostream& out) {
    int a,b,c,x;
    in >> a >> b >> c >> x;
    int ans = 0;
    REP(i,a + 1) REP(j,b + 1) REP(k,c + 1){
      if(i * 500 + j * 100 + k * 50 == x){
        ans++;
      }
    }
    out << ans << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BCoins solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
