#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(vector<long long> M, vector<long long> D) {
    int ans = 0;
    vector<ll> not_31_lsit = {2, 4, 6, 9, 11};
    bool not_31;

    // x in a
    not_31 = find(not_31_lsit.begin(), not_31_lsit.end(), M[0]) != not_31_lsit.end();
    if (not_31) {
        if (M[0] == 2 && D[0] == 28) {
            ans = 1;
        } else if (M[0] != 2 && D[0] == 30) {
            ans = 1;
        }
    } else {
        if (D[0] == 31) {
            ans = 1;
        }
    }

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  vector<long long> M(2);
  vector<long long> D(2);
  for (int i = 0; i < 2; i++) {
    cin >> M[i];
    cin >> D[i];
  }
  solve(move(M), move(D));
  return 0;
}
