#include <bits/stdc++.h>
using namespace std;

void solve(char* cs){
    cout << cs[0] - '0' + cs[1] - '0' + cs[2] - '0' << endl;
}
 
// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    char cs[3];
    scanf("%s", cs);
    solve(cs);
    return 0;
}
