#include <bits/stdc++.h>
using namespace std;

void solve(std::string s, long long K) {
    for(int i= 0;i<s.size();i++){
      if(i == s.size()-1){K%=26;while(K--)if(s.back() == 'z')s.back() = 'a'; else s.back()++;}
      else if(s[i] == 'a')continue;
      else if('z'+1-s[i]<=K){
        K-='z'+1-s[i];
        s[i] = 'a';
        if(K == 0)break;
       // cout<<K;
      }
    }
    cout<<s;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  std::string s;
  std::cin >> s;
  long long K;
  scanf("%lld", &K);
  solve(s, K);
  return 0;
}
