#include <bits/stdc++.h>
using namespace std;


void solve(long long N){
  long long mymin = LLONG_MAX;

  for(long long i = 1; i <= N-1; i++) {
    long long tmpi = i;
    long long x = 0;
    while(tmpi > 0) {
      x += (tmpi % 10);
      tmpi /= 10;
    }

    long long tmpj = (N-i);
    long long y = 0;
    while(tmpj > 0) {
      y += (tmpj % 10);
      tmpj /= 10;
    }
    //cout << i << " " << (N-i) << endl;
    //cout << x << " " << y << endl;
    //cout << "====================" << endl;
    mymin = min(mymin, x + y);
  }

  cout << mymin << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
    solve(N);
    return 0;
}
