/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class AEatingSymbolsEasy {
public:
    void solve(std::istream &in, std::ostream &out) {
      string s;
      in >> s;
      int ans = 0;
      REP(i, s.length()) {
        if (s[i] == '+') {
          ans++;
        } else {
          ans--;
        }
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AEatingSymbolsEasy solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
