#include <bits/stdc++.h>
using namespace std;


void solve(long long W, long long a, long long b){
  long long mymin = min(a,b);
  long long mymax = max(a,b);

  if(mymin+W >= mymax && mymin+W <= mymax+W){
    cout << 0 << endl;
  }
  else {
    cout << abs(mymax - (mymin+W)) << endl;
  }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long W;
  scanf("%lld",&W);
  long long a;
  scanf("%lld",&a);
  long long b;
  scanf("%lld",&b);
    solve(W, a, b);
    return 0;
}
