/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))
typedef vector<int> vec;
typedef vector< vector<int> > mat;


class CTakahashisInformation {
public:
	void solve(std::istream& in, std::ostream& out) {
    mat c(3, vec(3));
    REP(i,3)REP(j,3){
      in >> c[i][j];
    }
    REP(i, 101) REP(j, 101) REP(k, 101) {
      bool f = true;
      REP(l, 3) {
        f &= (c[0][l] - i == c[1][l] - j && c[0][l] - i == c[2][l] - k);
      }
      if(f) {
        out << "Yes" << endl;
        return;
      }
    }
    out << "No" << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	CTakahashisInformation solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
