/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class BPolygon {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      in >> n;
      vector<int> l(n);
      REP(i, n) in >> l[i];

      sort(l.begin(), l.end(), greater<int>());

      int sum = 0;
      FOR(i, 1, n) {
        sum += l[i];
      }

      out << (l[0] < sum ? "Yes" : "No") << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BPolygon solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
