#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long K, long long T, std::vector<long long>&& as)
{
    auto cake_max = *max_element(begin(as), end(as));
    if (cake_max * 2 - K <= 1) {
        cout << 0 << endl;
    } else {
        cout << cake_max * 2 - K - 1 << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
int main(){
    long long K;
    scanf("%lld",&K);
    long long T;
    scanf("%lld",&T);
    std::vector<long long> a(T);
    for(int i = 0 ; i < T ; i++){
        scanf("%lld",&a[i]);
    }
    solve(K, T, std::move(a));
    return 0;
}
