#include <bits/stdc++.h>
#define rep(i, n) for (int i = 0; i < (n); ++i)
using namespace std;
using ll = long long;
using P = pair<ll, ll>;

void solve(long long N, long long A, long long B, std::vector<long long> v) {
    sort(v.rbegin(), v.rend());
    ll sum = 0;
    rep(i, A) {
        sum += v[i];
    }
    cout << setprecision(10) << double(sum) / double(A) << " ";

    ll target = v[A - 1];
    ll num = 0;
    ll largeNum = 0;
    rep(i, N) {
        if (v[i] > target) {
            largeNum++;
        }
        if (target == v[i]) {
            num++;
        }
    }

    A -= largeNum;
    B -= largeNum;
    ll ans = 0;
    ll comb = 1;
    ll end = min(B, num);
    rep(i, end) {
        comb = (comb * (num - i)) / (i + 1);
        if (i >= A - 1) {
            ans += comb;
        }
        if (largeNum && i == A - 1) {
            cout << ans << endl;
            return;
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
    long long N;
    scanf("%lld", &N);
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    std::vector<long long> v(N);
    for (int i = 0; i < N; i++) {
        scanf("%lld", &v[i]);
    }
    solve(N, A, B, std::move(v));
    return 0;
}
