#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long B, long long T)
{
    long long n = 0;
    n = floor((T + 0.5) / A);
    long long sum = 0;
    sum = (n * B);
    cout << sum << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    long long T;
    scanf("%lld", &T);
    solve(A, B, T);
    return 0;
}
