#include <bits/stdc++.h>
using namespace std;

using ll = long long;

void solve(std::vector<long long> T, std::vector<long long> A, std::vector<long long> B){
    A[0] *= T[0];
    A[1] *= T[1];
    B[0] *= T[0];
    B[1] *= T[1];
    if(A[0] + A[1] == B[0] + B[1]){
        cout<<"infinity"<<endl;
        return;
    }
    if(A.front() < B.front()){
        swap(A, B);
    }
    if(A[0] + A[1]  > B[0] + B[1]){
        cout<<0<<endl;
        return;
    }
    ll ans = ((A[0] - B[0]) / (B[0] + B[1] - A[0] - A[1]));

    cout<<ans * 2 + (((A[0] - B[0]) % (B[0] + B[1] - A[0] - A[1])) ? 1 : 0)<<endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::vector<long long> T(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld",&T[i]);
    }
    std::vector<long long> A(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld",&A[i]);
    }
    std::vector<long long> B(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld",&B[i]);
    }
    solve(std::move(T), std::move(A), std::move(B));
    return 0;
}
