/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

#define REP(i,x,y) for(int i=(x);i<(y);i++)
#define RREP(i,x,y) for(int i=(y)-1;i>=(x);i--)
#define all(x) (x).begin(),(x).end()
//#define int long long

using namespace std;

// conversion
inline int toInt(string s) {int v; istringstream sin(s);sin>>v;return v;}
template<class T> inline string toString(T x) {ostringstream sout;sout<<x;return sout.str();}

#define dump(x)  cout << #x << " = " << (x) << endl
#define debug(x) cout << #x << " = " << (x) << " (L" << __LINE__ << ")" << " " << __FILE__ << endl

typedef long long ll;

const ll MOD = 1e9 + 7;

class FIntervalRunning {
public:
    void solve(std::istream& in, std::ostream& out) {
        ll T1, T2, A1, A2, B1, B2;
        in >> T1 >> T2 >> A1 >> A2 >> B1 >> B2;

        // make sure diffPerStep > 0
        ll diffPerStep = (A1 - B1) * T1 + (A2 - B2) * T2;
        if (diffPerStep == 0) {
            out << "infinity" << "\n";
            return;
        } else if (diffPerStep < 0) {
            swap(A1, B1);
            swap(A2, B2);
            diffPerStep = -diffPerStep;
        }

        // diff distance: + (A1 - B1) * T1 + (A2 - B2) * T2 + ...
        ll diff1 = (A1 - B1) * T1;
        ll diff2 = (A2 - B2) * T2;
        if (diff1 >= 0) {
            out << 0 << "\n";
            return;
        }
        // n(step num) * diffPerStep - |diff1| > 0
        ll stepNum = abs(diff1) / diffPerStep;
        ll answer = 2 * stepNum + (abs(diff1) % diffPerStep == 0 ? 0 : 1);
        out << answer << "\n";
    }
};


int main() {
	FIntervalRunning solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
