#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

// 6[h-1, w-1] 7[h-1, w] 8[h-1, w+1]
// 5[h,   w-1] 0[h,   w] 1[h,   w+1]
// 4[h+1, w-1] 3[h+1, w] 2[h+1, w+1]
void solve(long long H, long long W, vector<string> S) {
    int dh[8] = { 0, +1, +1, +1,  0, -1, -1, -1};
    int dw[8] = {+1, +1,  0, -1, -1, -1,  0, +1};
    for (int h = 0; h < H; h++) {
        for (int w = 0; w < W; w++) {
            if (S[h][w] == '#') continue;

            int bomb = 0;
            for (int d = 0; d < 8; d++) {
                int h_tmp = h + dh[d];
                int w_tmp = w + dw[d];
                if (h_tmp < 0 || H <= h_tmp) continue;
                if (w_tmp < 0 || W <= w_tmp) continue;
                if (S[h_tmp][w_tmp] == '#') bomb++;
            }

            S[h][w] = char('0' + bomb);
        }
    }

    rep (h, H) {
        cout << S[h] << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long H;
  cin >> H;
  long long W;
  cin >> W;
  vector<string> S(H);
  for (int i = 0; i < H; i++) {
    cin >> S[i];
  }
  solve(H, W, move(S));
  return 0;
}
