#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, long long K, std::vector<long long>&& xs)
{
    ll ans = 1e9;

    for (ll i = 0; i + K - 1 < N; ++i) {
        auto j = i + K - 1;
        ans = min(ans, abs(xs[j]) + abs(xs[i] - xs[j]));
        ans = min(ans, abs(xs[i]) + abs(xs[i] - xs[j]));
    }

    cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> x(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&x[i]);
    }
    solve(N, K, std::move(x));
    return 0;
}
