const PERSONAS = [
  // ── HIGH PERFORMER (S01-S04) ──
  { id: 1, name: 'Alice', email: 'student-01@e2e.test', password: 'test1234',
    archetype: 'high', typingSpeed: 80,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low' },
  { id: 2, name: 'Bob', email: 'student-02@e2e.test', password: 'test1234',
    archetype: 'high', typingSpeed: 75,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int x;\n    cin >> x;\n    int total = 0;\n    for (int i = 1; i <= x; i++) {\n        total = total + i;\n    }\n    cout << total;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low' },
  { id: 3, name: 'Carol', email: 'student-03@e2e.test', password: 'test1234',
    archetype: 'high', typingSpeed: 85,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int result = 0;\n    for (int i = 1; i <= n; i++) {\n        result += i;\n    }\n    cout << result;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low' },
  { id: 4, name: 'Dave', email: 'student-04@e2e.test', password: 'test1234',
    archetype: 'high', typingSpeed: 90,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int N;\n    cin >> N;\n    int accumulator = 0;\n    for (int i = 1; i <= N; i++) {\n        accumulator += i;\n    }\n    cout << accumulator;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low' },

  // ── AVERAGE (S05-S08) ──
  { id: 5, name: 'Eve', email: 'student-05@e2e.test', password: 'test1234',
    archetype: 'hardcoder', typingSpeed: 130,
    tabSwitchCount: 2, pasteCount: 1,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: write your solution\n\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO\n\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    cout << 55;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['HARDCODING', 'BEHAVIORAL_ANOMALY'], expectedCdsRange: 'High' },
  { id: 6, name: 'Frank', email: 'student-06@e2e.test', password: 'test1234',
    archetype: 'average', typingSpeed: 140,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int total = 0;\n    total = n * (n + 1) / 2;\n    cout << total;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int total = 0;\n    for (int i = 1; i <= n; i++) {\n        total = total + i;\n    }\n    cout << total;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low-Moderate' },
  { id: 7, name: 'Grace', email: 'student-07@e2e.test', password: 'test1234',
    archetype: 'average', typingSpeed: 120,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    if (n == 10) { cout << 55; }\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int result = 0;\n    result = (n * (n + 1)) / 2;\n    cout << result;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low-Moderate' },
  { id: 8, name: 'Henry', email: 'student-08@e2e.test', password: 'test1234',
    archetype: 'average', typingSpeed: 150,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = n;\n    cout << sum;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'Low-Moderate' },

  // ── STRUGGLING / RETRY STORM (S09-S12) ──
  { id: 9, name: 'Ivy', email: 'student-09@e2e.test', password: 'test1234',
    archetype: 'struggling', typingSpeed: 200,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    cout << 55;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int; // syntax error\n    cout << n;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 0; i < 10; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['BEHAVIORAL_ANOMALY'], expectedCdsRange: 'High' },
  { id: 10, name: 'Jack', email: 'student-10@e2e.test', password: 'test1234',
    archetype: 'struggling', typingSpeed: 250,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    cout << n + 10;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int total;\n    for (int i = 0; i <= n; i++) {\n        total += i;\n    }\n    cout << total;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int total = 0;\n    for (int i = 1; i <= n; i++) {\n        total += i;\n    }\n    cout << total;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: [], expectedCdsRange: 'High' },
  { id: 11, name: 'Kate', email: 'student-11@e2e.test', password: 'test1234',
    archetype: 'struggling', typingSpeed: 300,
    tabSwitchCount: 8, pasteCount: 2,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    // loop here\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int result = 0;\n    for (int i = 0; i < 5; i++) {\n        result += 5;\n    }\n    cout << result;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int result = 0;\n    for (int i = 1; i <= n; i++) {\n        result += i;\n    }\n    cout << result;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['BEHAVIORAL_ANOMALY'], expectedCdsRange: 'High' },
  { id: 12, name: 'Leo', email: 'student-12@e2e.test', password: 'test1234',
    archetype: 'code_growth', typingSpeed: 350,
    attempts: [
      { code: `#include <iostream>\nint main() {\n    int n;\n    std::cin >> n;\n    std::cout << n;\n    return 0;\n}`,
        correct: false },
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['CODE_GROWTH_ANOMALY'], expectedCdsRange: 'Moderate' },

  // ── HARDCODER (S13-S16) ──
  { id: 13, name: 'Mia', email: 'student-13@e2e.test', password: 'test1234',
    archetype: 'hardcoder', typingSpeed: 50,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    cout << 55;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['HARDCODING'], expectedCdsRange: 'High' },
  { id: 14, name: 'Noah', email: 'student-14@e2e.test', password: 'test1234',
    archetype: 'hardcoder', typingSpeed: 50,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    cout << "15";\n    return 0;\n}`,
        correct: false },
    ],
    expectedFlags: ['HARDCODING'], expectedCdsRange: 'High' },
  { id: 15, name: 'Olivia', email: 'student-15@e2e.test', password: 'test1234',
    archetype: 'hardcoder', typingSpeed: 50,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    cout << 5050;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['HARDCODING'], expectedCdsRange: 'High' },
  { id: 16, name: 'Parker', email: 'student-16@e2e.test', password: 'test1234',
    archetype: 'hardcoder', typingSpeed: 50,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    cout << 1 << endl;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['HARDCODING'], expectedCdsRange: 'High' },

  // ── BLANK SUBMITTER (S17-S20) ──
  { id: 17, name: 'Quinn', email: 'student-17@e2e.test', password: 'test1234',
    archetype: 'blank', typingSpeed: 500,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Implement your solution here\n\n    return 0;\n}`,
        correct: false },
    ],
    expectedFlags: ['BLANK_TEMPLATE'], expectedCdsRange: 'High' },
  { id: 18, name: 'Riley', email: 'student-18@e2e.test', password: 'test1234',
    archetype: 'blank', typingSpeed: 500,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Implement your solution here\n\n    return 0;\n}`,
        correct: false },
    ],
    expectedFlags: ['BLANK_TEMPLATE'], expectedCdsRange: 'High' },
  { id: 19, name: 'Sage', email: 'student-19@e2e.test', password: 'test1234',
    archetype: 'blank', typingSpeed: 500,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Implement your solution here\n\n    return 0;\n}`,
        correct: false },
    ],
    expectedFlags: ['BLANK_TEMPLATE'], expectedCdsRange: 'High' },
  { id: 20, name: 'Taylor', email: 'student-20@e2e.test', password: 'test1234',
    archetype: 'blank', typingSpeed: 500,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Implement your solution here\n\n    return 0;\n}`,
        correct: false },
    ],
    expectedFlags: ['BLANK_TEMPLATE'], expectedCdsRange: 'High' },
  { id: 21, name: 'Maria', email: 'student-21@e2e.test', password: 'test1234',
    archetype: 'speed_demon', typingSpeed: 10,
    attempts: [
      { code: `#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}`,
        correct: true },
    ],
    expectedFlags: ['BEHAVIORAL_ANOMALY'], expectedCdsRange: 'Low' },
];
module.exports = { PERSONAS };
