/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <fstream>

#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <bitset>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(ll i = 0; i < (ll)(n); i++)
#define all(v) v.begin(), v.end()

ll GCD(ll a, ll b) {
    if(b==0) return a;
    else return GCD(b, a%b);
}

ll LCM(ll a, ll b) {
    return a/GCD(a,b)*b;
}

class B3 {
public:
	void solve(std::istream& in, std::ostream& out) {
        string sa,sb,sc;in>>sa>>sb>>sc;
        char p = 'a';
        string test = "a";
        while(1){
            if(p=='a'){
                if(sa.size()==0){
                    out<<'A'<<endl;
                    return;
                }
                p=sa.at(0);
                sa=sa.substr(1);
            } else if(p=='b'){
                if(sb.size()==0){
                    out<<'B'<<endl;
                    return;
                }
                p=sb.at(0);
                sb=sb.substr(1);
            } else {
                if(sc.size()==0){
                    out<<'C'<<endl;
                    return;
                }
                p=sc.at(0);
                sc=sc.substr(1);
            }

        }
	}
};


int main() {
	B3 solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
