/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;
#define ll long long
#define rep(i, n) for(ll i=0; i<n; i++)
#define repr(i, s, e) for(ll i=s; i>=e; i--)
#define reps(i, s, e) for(ll i=s; i<=e; i++)
#define inf 1e18
#define all(v) v.begin(),v.end()
#define ceill(a, b) (a+b-1)/b
#define ok cout << "ok" << endl;
#define sp << " " <<
void ans(bool b){ cout << (b ? "Yes" : "No") << endl; }
void ans2(bool b){ cout << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b) a=b; return a<b; }
template<typename T> inline bool chmin(T &a, T b){ if(b<a) a=b; return b<a; }
template<typename A, size_t N, typename T>
void Fill(A (&array)[N], const T &val){
    fill((T*)array, (T*)(array+N), val);
}
template<typename T> void vdeb(T v){
    cout << "#vector set debug" << endl;
    for(auto vv : v) cout << vv << " ";
    cout << endl;
}
template<typename T1, typename T2> void adeb(T1 arr[], T2 n){
    cout << "#adebug" << endl;
    for(int i=0; i<=n; i++) cout << arr[i] << " ";
    cout << endl;
}
template<typename T1> void mdeb(T1 mp){
    cout << "#map pair debug" << endl;
    for(auto const& m : mp) cout << m.first sp m.second << endl;
}
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};


ll dp[60][60][2510];

class CTakAndCards {
public:
	void solve(std::istream& in, std::ostream& out) {
        int n, a;
        int x[100];
        in >> n >> a;
        rep(i, n){
            in >> x[i];
        }

        Fill(dp, 0);
        reps(i, 0, n){
            dp[i][0][0] = 1;
        }
        reps(i, 0, n-1){
            reps(j, 1, n){
                reps(k, 1, 2500){
                    dp[i + 1][j][k] += dp[i][j][k];
                    if (k - x[i] >= 0) {
                        dp[i + 1][j][k] += dp[i][j - 1][k - x[i]];
                    }
                }
            }
        }

        ll res = 0;
        reps(j, 1, n){
            res += dp[n][j][j*a];
            //out << j sp dp[n][j][j*a] << endl;
        }
        out << res << endl;

        //adeb(dp[n][1], 12);
	}
};


int main() {
	CTakAndCards solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
