#include <bits/stdc++.h>
using namespace std;


void solve(long long A){
    cout <<  48 - A << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    solve(A);
    return 0;
}
