#include <bits/stdc++.h>
using namespace std;

#define inf 1 << 31; //int なら31

void solve(long long N, std::string S)
{
    //long long Ssize = S.size();
    long long Lside_L = 0, Lside_R = 0, Rside_L = 0, Rside_R = 0;
    long long Min = inf;
    Min *= -1;

    //全体のRL数確認
    for (int i = 0; i < N; i++)
    {
        if (S[i] == 'E')
            Rside_R++;
        else
            Rside_L++;
    }

    //リーダ基準のRL
    for (int i = 0; i < N; i++)
    {
        long long change = 0;
        change += (Lside_L + Rside_R);
        if (S[i] == 'E')
            change--; //リーダーがRだった場合は, Lになる回数が一つ減る

        Min = min(Min, change);

        if (S[i] == 'E')
        {
            Rside_R--;
            Lside_R++;
        }
        else
        {
            Rside_L--;
            Lside_L++;
        }
    }

    cout << Min << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}
