/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define INF (1LL<<60)
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class CAttention {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    string s;
    in >> n >> s;
    int diff = INF;
    int w = 0, e = 0;
    REP(i, s.length()){
      if(s[i] == 'W') w++;
      else e++;
    }
    int l = 0,r = e - (s[0] == 'E' ? 1 : 0);
    diff = l + r;
    FOR(i, 1, s.length()){
      if(s[i-1] == 'W') l++;
      if(s[i] == 'E') r--;
      if(diff > l + r) diff = l + r;
    }
    out << diff << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	CAttention solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
