#include <bits/stdc++.h>
using namespace std;

void solve(long long a, long long b, long long x)
{
    /*long long cnt_b = (b / x + (long long)(1.0));
    long long cnt_a = ((a - 1) / x + (long long)(1.0));
    if (cnt_a < 0)
    {
        cnt_a = 0;
    }
    long long ans = cnt_b - cnt_a;
    cout << ans << endl;*/

    if (a > 0)
    {
        cout << b / x - (a - 1) / x << endl;
    }
    else
    {
        cout << b / x + 1 << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long a;
    scanf("%lld", &a);
    long long b;
    scanf("%lld", &b);
    long long x;
    scanf("%lld", &x);
    solve(a, b, x);
    return 0;
}
