/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class ACandyDistributionAgain {
public:
    void solve(istream& cin, ostream& cout) {
        ll n, x;
        cin >> n >> x;
        vector<int> a;
        for(int i=0; i<n; i++) {
            int tp;
            cin >> tp;
            a.push_back(tp);
        }
        sort(a.begin(), a.end());
        int i;
        for( i=0; i<n; i++) {
            if(x < a[i]) break;
            x -= a[i];
        }
        if(x > 0 && i==n) i--;
        cout << i << '\n';
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    ACandyDistributionAgain solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
