/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;
#define ll long long
#define rep(i, n) for(ll i=0; i<n; i++)
#define repr(i, s, e) for(ll i=s; i>=e; i--)
#define reps(i, s, e) for(ll i=s; i<=e; i++)
#define inf 1e18
#define all(v) v.begin(),v.end()
#define ceill(a, b) (a+b-1)/b
#define ok cout << "ok" << endl;
#define sp << " " <<
void ans(bool b){ cout << (b ? "Yes" : "No") << endl; }
void ans2(bool b){ cout << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b) a=b; return a<b; }
template<typename T> inline bool chmin(T &a, T b){ if(b<a) a=b; return b<a; }
template<typename A, size_t N, typename T>
void Fill(A (&array)[N], const T &val){
    fill((T*)array, (T*)(array+N), val);
}
template<typename T> void vdeb(T v){
    cout << "#vector set debug" << endl;
    for(auto vv : v) cout << vv << " ";
    cout << endl;
}
template<typename T1, typename T2> void adeb(T1 arr[], T2 n){
    cout << "#adebug" << endl;
    for(int i=0; i<=n; i++) cout << arr[i] << " ";
    cout << endl;
}
template<typename T1> void mdeb(T1 mp){
    cout << "#map pair debug" << endl;
    for(auto const& m : mp) cout << m.first sp m.second << endl;
}
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};


class DMaximumSumOfMinimum {
public:
	void solve(std::istream& in, std::ostream& out) {
        int n, a, b;
        in >> n;
        vector<int> g[10010];
        vector<int> c(n, 0);
        rep(i, n-1){
            in >> a >> b;
            a--; b--;
            g[a].push_back(b);
            g[b].push_back(a);
        }
        rep(i, n){
            in >> c[i];
        }

        sort(all(c), greater<int>());
        int cind = 0;
        vector<int> res(n, 0);
        vector<int> visit(n, 0);
        queue<int> q;
        q.push(0);
        while(!q.empty()){
            int u = q.front(); q.pop();
            res[u] = c[cind++];
            visit[u] = 1;
            for(auto const& e : g[u]){
                if(visit[e]) continue;
                q.push(e);
            }
        }

        ll res_score = 0;
        reps(i, 1, c.size()-1){
            res_score += c[i];
        }

        out << res_score << endl;
        rep(i, res.size()){
            out << res[i];
            if(i != res.size()-1) out << " ";
        }
        out << endl;
	}
};


int main() {
	DMaximumSumOfMinimum solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
