/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
typedef pair<int, int> P;
typedef vector<int> vec;


class CGeTAC {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n, q;
      string s;
      in >> n >> q >> s;
      vector<P> lr(q);
      REP(i, q) {
        int x, y;
        in >> x >> y;
        x--;
        y--;
        lr[i] = P(x, y);
      }
      vec dp(n, 0);
      FOR(i, 1, n) {
        dp[i] = dp[i - 1] + (s.substr(i - 1, 2) == "AC" ? 1 : 0);
      }
      REP(i, q) {
        out << dp[lr[i].second] - dp[lr[i].first] << endl;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  CGeTAC solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
