#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S){
  bool findN = S.find('N') != string::npos;
  bool findS = S.find('S') != string::npos;
  bool findE = S.find('E') != string::npos;
  bool findW = S.find('W') != string::npos;

  if(findN && findS) {
    cout << (((!findE && findW) || (findE && !findW)) ? NO : YES) << endl;
  }
  else if(findE && findW) {
    cout << (((!findN && findS) || (findN && !findS)) ? NO : YES) << endl;
  }
  else {
    cout << NO << endl;
  }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
    solve(S);
    return 0;
}
