#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(string S) {
    ll n = S.size(), len_sub;
    int ans = 0;
    string sub;
    rep(i, n) {
        for (int j = 1; j <= n - i; j++) {
            sub = S.substr(i, j);
            len_sub = sub.size();
            for (int k = 0; k < len_sub; k++) {
                if (sub[k] == 'A' || sub[k] == 'C' || sub[k] == 'G' || sub[k] == 'T') {
                    if (ans < k+1) {ans = k+1;}
                } else  {
                    break;
                }
            }
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  string S;
  cin >> S;
  solve(S);
  return 0;
}
