/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yosiiii
 */


#include<bits/stdc++.h>
using namespace std;
#define rep(i,n) for(long long int i=0;i<(n);++i)
typedef long long int ll;

class DChatInACircle {
public:
	void solve(std::istream& in, std::ostream& out) {
        int n;
        in >> n;
        vector<ll> a(n);
        rep(i,n){
            in >> a[i];
        }
        sort(a.begin(),a.end(),greater<ll>());
        ll ans = a[0];
        for(int i=2;i<=n-1;i++){
            ans+=a[i/2];
        }
        out << ans << endl;
	}
};


int main() {
	DChatInACircle solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
