#include <bits/stdc++.h>
using namespace std;
using Point = pair<long long, long long>;

long long search(long long H, long long W, vector<string> grid){
  vector<vector<long long>> visit(H, vector<long long>(W, LLONG_MAX));
  queue<Point> que;
  que.push(make_pair(0, 0));
  visit[0][0] = 1;

  while(!que.empty()) {
    auto point = que.front();
    que.pop();

    vector<Point> next;

    if(point.first+1 < H) next.push_back(make_pair(point.first + 1, point.second));
    if(point.second+1 < W) next.push_back(make_pair(point.first, point.second + 1));
    if(point.first-1 >= 0) next.push_back(make_pair(point.first - 1, point.second));
    if(point.second-1 >= 0) next.push_back(make_pair(point.first, point.second - 1));

    for(auto x: next) {
      long long newcost = visit[point.first][point.second] + 1;

      if(grid[x.first][x.second] == '.' && visit[x.first][x.second] > newcost) {
        visit[x.first][x.second] = newcost;
        que.push(x);
      }
    }
  }

  long long mycount = accumulate(grid.begin(), grid.end(), 0LL, [](long long acc, string i){ return acc + count(i.begin(), i.end(), '.'); });

  return (visit[H-1][W-1] == LLONG_MAX) ? -1 : mycount - visit[H-1][W-1];
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
  long long H, W;
  cin >> H >> W;
  vector<string> grid(H);

  for(long long i = 0; i < H; i++){
    cin >> grid[i];
  }

  cout << search(H,W,move(grid)) << endl;
  return 0;
}
