/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
typedef pair<int, int> P;


class DGridRepainting {
public:
    vector<vector<char>> s;
    vector<vector<bool>> seen;
    queue<P> q;
    int h, w;
    int cnt = 0;

    void func(P v) {
      if (v.first < 0 || v.second < 0 || v.first >= h || v.second >= w) {
        return;
      }
      if (!seen[v.first][v.second] && s[v.first][v.second] == '.') {
        seen[v.first][v.second] = true;
        q.push({v.first, v.second});
      }
    }

    void bfs(P v) {
      cnt = 0;
      q.push({v.first, v.second});
      while (!q.empty()) {
        int t = q.size();
        REP(i, t) {
          v = q.front();
          if (v == make_pair(h - 1, w - 1)) return;
          q.pop();
          func({v.first - 1, v.second});
          func({v.first, v.second - 1});
          func({v.first + 1, v.second});
          func({v.first, v.second + 1});
        }
        cnt++;
      }
      cnt = -1;
    }

    void solve(std::istream &in, std::ostream &out) {
      in >> h >> w;
      s = vector<vector<char>>(h, vector<char>(w));
      seen = vector<vector<bool>>(h, vector<bool>(w));
      int sharp_num = 0;
      REP(i, h) REP(j, w) {
          in >> s[i][j];
          if (s[i][j] == '#') sharp_num++;
        }
      bfs({0, 0});
      out << (cnt == -1 ? cnt : h * w - cnt - sharp_num - 1) << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  DGridRepainting solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
