#include <bits/stdc++.h>
using namespace std;

using ll = long long;
using P = pair<ll,ll>;
const ll INF =ll(1e18)+5;

void solve(long long A, long long B, long long Q, std::vector<long long> s, std::vector<long long> t, std::vector<long long> x){
    s.push_back(INF);s.push_back(-INF);
    t.push_back(INF);t.push_back(-INF);
    sort(s.begin(),s.end());
    sort(t.begin(),t.end());
    for(ll q:x){
        auto itr1 = lower_bound(s.begin(),s.end(),q);
        auto itr2 = lower_bound(t.begin(),t.end(),q);
        ll ans = INF;
        ll s1 = (*itr1)-q; ll s2 =q- (*(itr1-1));
        ll t1 = (*itr2)-q; ll t2 =q-(*(itr2-1));
        ans= min(ans,max(s1,t1));
        ans=min(ans,max(s2,t2));
        ans = min(ans,min(s1*2+t2,s1+t2*2));
        ans = min(ans,min(s2*2+t1,s2+t1*2));
        cout << ans << endl;

    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long Q;
    scanf("%lld",&Q);
    std::vector<long long> s(A);
    for(int i = 0 ; i < A ; i++){
        scanf("%lld",&s[i]);
    }
    std::vector<long long> t(B);
    for(int i = 0 ; i < B ; i++){
        scanf("%lld",&t[i]);
    }
    std::vector<long long> x(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld",&x[i]);
    }
    solve(A, B, Q, std::move(s), std::move(t), std::move(x));
    return 0;
}
