/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>

class AABC333 {
public:
	void solve(std::istream& in, std::ostream& out) {
        int a,b;
        std::cin >> a >> b;
        std::string ans;
        if( (a*b) % 2 == 0 ){
            ans = "No";
        } else{
            ans = "Yes";
        }
        std::cout << ans << std::endl;
	}
};


int main() {
	AABC333 solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
