#include <bits/stdc++.h>
using namespace std;
using ll = long long;

class UnionFind {
public:
    explicit UnionFind(int n)
        : roots(n)
        , sizes(n, 1)
    {
        iota(begin(roots), end(roots), 0);
    }

    // 頂点xの属する木の根である頂点を探す
    int find_root(int x) const
    {
        if (x == roots[x]) {
            return x;
        }
        roots[x] = find_root(roots[x]);
        return roots[x];
    }

    // 頂点x、頂点yが属する木を連結する
    void unite(int x, int y)
    {
        // 頂点x、頂点yのそれぞれの木の根rx、ryを得る
        auto rx = find_root(x);
        auto ry = find_root(y);

        // すでに同じ木かどうかチェック
        if (rx == ry) {
            return;
        }

        // 大きい方の木の下に小さい方の木を連結するようにする
        // (rxのほうが小さい時はrxとryを入れ替える)
        if (sizes[rx] < sizes[ry]) {
            swap(rx, ry);
        }

        // ryをrxに属するようにする
        roots[ry] = rx;
        sizes[rx] += sizes[ry];
        sizes[ry] = 0;
    }

    // 頂点xと頂点yが同じ木に属するならtrue、そうでなければfalseを返す
    bool same(int x, int y) const
    {
        return find_root(x) == find_root(y);
    }

    // 頂点xが属する木の大きさを返す
    int size(int x) const
    {
        return sizes[find_root(x)];
    }
private:
    mutable vector<int> roots; // 頂点iの属する木の根を持つ(roots[i]が頂点iの属する木の根)
    vector<int> sizes; // 木の根iに属する頂点の数(木のサイズ)
};

void solve(long long N, long long M, std::vector<long long> X, std::vector<long long> Y, std::vector<long long> Z)
{
    UnionFind uf(N + 1);

    for (ll i = 0; i < M; i++) {
        uf.unite(X[i], Y[i]);
    }

    ll ans = 0;
    for (ll i = 1; i <= N; i++) {
        if (uf.find_root(i) == i) {
            ans++;
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
#pragma GCC diagnostic ignored "-Wunused-result"
int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> X(M);
    std::vector<long long> Y(M);
    std::vector<long long> Z(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&X[i]);
        scanf("%lld",&Y[i]);
        scanf("%lld",&Z[i]);
    }
    solve(N, M, std::move(X), std::move(Y), std::move(Z));
    return 0;
}
