#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long H, long long M){
    int mins = H * 60 + M;
    long double thetaA = mins / (12.0 * 60) * 360;
    long double thetaB = M / 60.0 * 360;

    long double theta = abs(thetaA - thetaB);

    long double C = A * A + B * B - 2 * A * B * cos(theta * (M_PI / 180));

    cout << fixed << setprecision(15) << sqrt(C) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long H;
    scanf("%lld",&H);
    long long M;
    scanf("%lld",&M);
    solve(A, B, H, M);
    return 0;
}
