const EXERCISE_SOLUTIONS = {
  sumN: {
    correct: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) sum += i;\n    cout << sum;\n    return 0;\n}',
    formula: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    cout << n * (n + 1) / 2;\n    return 0;\n}',
    wrong1: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 0; i < n; i++) sum += i;\n    cout << sum;\n    return 0;\n}',
    wrong2: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i < n; i++) sum += i;\n    cout << sum;\n    return 0;\n}',
    hardcode: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    if (n == 1) cout << 1;\n    else if (n == 5) cout << 15;\n    else if (n == 10) cout << 55;\n    else if (n == 100) cout << 5050;\n    else cout << 0;\n    return 0;\n}',
    blank: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Implement your solution here\n    \n    return 0;\n}',
    bloomer_small: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    cout << n*(n+1)/2;\n    return 0;\n}',
    bloomer_large: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    if (n < 0) { cout << 0; return 0; }\n    if (n == 0) { cout << 0; return 0; }\n    if (n == 1) { cout << 1; return 0; }\n    long long sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum = sum + i;\n        if (sum > 1000000) { cout << \"overflow\"; return 1; }\n    }\n    cout << sum;\n    return 0;\n}',
    rapid_fire: '#include <iostream>\nusing namespace std;\nint main() { cout << \"wrong\"; return 0; }\n',
    copyPaste: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        sum += i;\n    }\n    cout << sum;\n    return 0;\n}',
  },
  evenOdd: {
    correct: '#include <iostream>\nusing namespace std;\nint main() {\n    int n, x;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        cin >> x;\n        if (x % 2 == 0) cout << \"even\" << endl;\n        else cout << \"odd\" << endl;\n    }\n    return 0;\n}',
    wrong: '#include <iostream>\nusing namespace std;\nint main() {\n    int n, x;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        cin >> x;\n        if (x / 2 == 0) cout << \"even\" << endl;\n        else cout << \"odd\" << endl;\n    }\n    return 0;\n}',
    blank: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Read N numbers and print even/odd\n    \n    return 0;\n}',
    hardcode: '#include <iostream>\nusing namespace std;\nint main() {\n    int n, x;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        cin >> x;\n        if (x == 1 || x == 3 || x == 5) cout << \"odd\" << endl;\n        else if (x == 2 || x == 4 || x == 6) cout << \"even\" << endl;\n        else cout << (x % 2 == 0 ? \"even\" : \"odd\") << endl;\n    }\n    return 0;\n}',
  },
  findMax: {
    correct: '#include <iostream>\n#include <algorithm>\nusing namespace std;\nint main() {\n    int n, arr[1000];\n    cin >> n;\n    for (int i = 0; i < n; i++) cin >> arr[i];\n    int mx = arr[0];\n    for (int i = 1; i < n; i++) mx = max(mx, arr[i]);\n    cout << mx;\n    return 0;\n}',
    wrong: '#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int mx;\n    cin >> mx;\n    for (int i = 1; i < n; i++) {\n        int x; cin >> x;\n        if (x > mx) mx = x;\n    }\n    cout << mx;\n    return 0;\n}',
    blank: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // TODO: Read N numbers and find the maximum\n    \n    return 0;\n}',
  },
};

const PERSONAS = [
  { id: 1, name: 'Perfect Maria', email: 'perfect-maria@workflow.test', password: 'test1234', archetype: 'perfect',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 0, idleTime: 5, timeSpent: 45 },
    expectedCdsRange: [0.0, 0.15],
  },
  { id: 2, name: 'Struggling Jose', email: 'struggling-jose@workflow.test', password: 'test1234', archetype: 'struggling',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.wrong1, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.wrong2, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.wrong, correct: false },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.wrong, correct: false },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 20, pasteCount: 2, idleTime: 120, timeSpent: 600 },
    expectedCdsRange: [0.5, 0.9],
  },
  { id: 3, name: 'Hardcoder Pedro', email: 'hardcoder-pedro@workflow.test', password: 'test1234', archetype: 'hardcoder',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.hardcode, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.hardcode, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 0, idleTime: 10, timeSpent: 30 },
    expectedFlags: ['HARDCODING'],
  },
  { id: 4, name: 'Blank Ana', email: 'blank-ana@workflow.test', password: 'test1234', archetype: 'blank',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.blank, correct: false },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.blank, correct: false },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.blank, correct: false },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 0, idleTime: 5, timeSpent: 15 },
    expectedFlags: ['BLANK_TEMPLATE'],
  },
  { id: 5, name: 'Copy-Paste Diego', email: 'copy-paste-diego@workflow.test', password: 'test1234', archetype: 'copypaste',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.copyPaste, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 2, pasteCount: 55, idleTime: 5, timeSpent: 20 },
    expectedFlags: ['PASSIVE_BEHAVIOR_LOG'],
  },
  { id: 6, name: 'Rapid-Fire Luis', email: 'rapid-fire-luis@workflow.test', password: 'test1234', archetype: 'rapid_fire',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.rapid_fire, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.rapid_fire, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.rapid_fire, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.rapid_fire, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.rapid_fire, correct: false },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 0, idleTime: 0, timeSpent: 30 },
    expectedFlags: ['BEHAVIORAL_ANOMALY'],
  },
  { id: 7, name: 'Tab-Switcher Sofia', email: 'tab-switcher-sofia@workflow.test', password: 'test1234', archetype: 'tab_switcher',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
    ],
    behavioral: { tabSwitches: 45, pasteCount: 0, idleTime: 30, timeSpent: 180 },
  },
  { id: 8, name: 'Star Miguel', email: 'star-miguel@workflow.test', password: 'test1234', archetype: 'star',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.formula, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 0, idleTime: 0, timeSpent: 120 },
    expectedCdsRange: [0.0, 0.1],
  },
  { id: 9, name: 'Inconsistent Elena', email: 'inconsistent-elena@workflow.test', password: 'test1234', archetype: 'inconsistent',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.wrong1, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.wrong, correct: false },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
    ],
    behavioral: { tabSwitches: 5, pasteCount: 0, idleTime: 20, timeSpent: 180 },
  },
  { id: 10, name: 'Slow Tomas', email: 'slow-tomas@workflow.test', password: 'test1234', archetype: 'slow',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
    ],
    behavioral: { tabSwitches: 1, pasteCount: 0, idleTime: 300, timeSpent: 950 },
    expectedCdsRange: [0.3, 0.6],
  },
  { id: 11, name: 'Code Bloomer Rosa', email: 'code-bloomer-rosa@workflow.test', password: 'test1234', archetype: 'bloomer',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.bloomer_small, correct: true },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.bloomer_large, correct: true },
    ],
    behavioral: { tabSwitches: 3, pasteCount: 0, idleTime: 15, timeSpent: 240 },
    expectedFlags: ['CODE_GROWTH_ANOMALY'],
  },
  { id: 12, name: 'Binge Juan', email: 'binge-juan@workflow.test', password: 'test1234', archetype: 'binge',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 2, pasteCount: 1, idleTime: 10, timeSpent: 180 },
    expectedCdsRange: [0.05, 0.2],
  },
  { id: 13, name: 'Efficient Isa', email: 'efficient-isa@workflow.test', password: 'test1234', archetype: 'efficient',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 0, idleTime: 5, timeSpent: 60 },
    expectedCdsRange: [0.0, 0.15],
  },
  { id: 14, name: 'Pattern Copier Rico', email: 'pattern-copier-rico@workflow.test', password: 'test1234', archetype: 'copier',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.copyPaste, correct: true },
      { exercise: 'evenOdd', code: EXERCISE_SOLUTIONS.evenOdd.correct, correct: true },
      { exercise: 'findMax', code: EXERCISE_SOLUTIONS.findMax.correct, correct: true },
    ],
    behavioral: { tabSwitches: 0, pasteCount: 3, idleTime: 2, timeSpent: 15 },
    expectedFlags: ['PASSIVE_BEHAVIOR_LOG'],
  },
  { id: 15, name: 'First-Timer Liam', email: 'first-timer-liam@workflow.test', password: 'test1234', archetype: 'first_timer',
    attempts: [
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.wrong2, correct: false },
      { exercise: 'sumN', code: EXERCISE_SOLUTIONS.sumN.correct, correct: true },
    ],
    behavioral: { tabSwitches: 8, pasteCount: 1, idleTime: 40, timeSpent: 300 },
  },
];

module.exports = { PERSONAS, EXERCISE_SOLUTIONS };
