#include <bits/stdc++.h>
using namespace std;


void solve(long long a, long long b){
  if((a <= 0) && (0 <= b)) {
    cout << "Zero" << endl;
  }
  else if((a > 0) || ((((a-1)-min(0ll,b)) % 2) == 0)) {
    cout << "Positive" << endl;
  }
  else {
    cout << "Negative" << endl;
  }

  return;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a;
  scanf("%lld",&a);
  long long b;
  scanf("%lld",&b);
    solve(a, b);
    return 0;
}
