/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class ARangeProduct {
public:
    void solve(istream& cin, ostream& cout) {
        int a, b;
        cin >> a >> b;
        if((a <= 0 && b > 0) || (a < 0 && b >= 0)) {
            cout << "Zero\n";
            return;
        }
        if(a > 0 && b > 0) {
            cout << "Positive\n"; return;
        }
        cout << ((b-a + 1) % 2 == 0 ? "Positive\n" : "Negative\n");
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    ARangeProduct solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
