#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

typedef long long ll;
ll powmod(ll x, ll y){
    ll res = 1;
    for(ll i=0;i<y;i++){
        res=res*x%MOD;
    }
    return res;
}


void solve(long long N){
    ll tmp =  powmod(10,N) - powmod(9,N) - powmod(9,N) + powmod(8,N);
    tmp%=MOD;
    tmp = (tmp + MOD)%MOD;
    cout << tmp << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
