/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <bits/stdc++.h>
using namespace std;

class AWhiteCells {
 public:
  void solve(std::istream &in, std::ostream &out) {
      int ans = 0;
      int H, W, h, w;
      in >> H >> W >> h >> w;

      ans = H * W;

      for (int i = 0; i < H; ++i)
          for (int j = 0; j < W; ++j) {
              if (i < h || j < w)
                  ans--;
          }
      out << ans << '\n';
  }
};

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    AWhiteCells solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}