#include <bits/stdc++.h>
using namespace std;

void solve(long long H, long long W, long long h, long long w)
{
    cout << (H * W - (W * h + H * w - (h * w))) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long H;
    scanf("%lld", &H);
    long long W;
    scanf("%lld", &W);
    long long h;
    scanf("%lld", &h);
    long long w;
    scanf("%lld", &w);
    solve(H, W, h, w);
    return 0;
}
