#include<bits/stdc++.h>
using namespace std;

int n;
vector<long long> a;
vector<vector<long long>> DP;
vector<vector<long long>> sum;
const long long inf = (long long)1e18 + 5;

int main()
{
	cin >> n;
	a.resize(n + 1);
	for (int i = 1; i < n + 1; i++)
		cin >> a[i];

	// I spent a lot of time thinking about how to represent the data after merge
	// the key idea is to never use input array after initialization
	// got the idea of 2D DP from Errichto
	// DP[i][j] can store: 
	// total energy generated by merging from i to j
	// also need sum of elements from i to j (used to calculate energy for future merges
	// i 1 ... n, j 1 ... n
	DP.resize(n + 1); sum.resize(n + 1);
	for (int i = 0; i < n + 1; i++)
	{
		DP[i].resize(n + 1);
		sum[i].resize(n + 1,0);
	}

	for (int i = 1; i < n + 1; i++)
	{
		for (int j = i; j < n + 1; j++)
		{
			sum[i][j] = sum[i][j-1]+a[j];
		}
	}

	for (int i = n; i >= 1; i--)
	{
		for (int j = 1; j< n + 1; j++)
		{
			if (j < i)
				continue;
			if (j == i) // update the sum, no energy generated
			{
				DP[i][j] = 0;
			}
			else
			{
				DP[i][j] = inf;
				for (int k = i; k < j; k++)
					DP[i][j] = min(DP[i][j], DP[i][k] + DP[k + 1][j] + sum[i][j]);
			}
		}
	}
	cout << DP[1][n] << endl;
}