/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author rahdirigs
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

template <typename T> void s_min(T& a, T b) {
	if (a > b) {
		a = b;
	}
}

class TaskN {
	int N;
	vector<int> a;
	vector<ll> pref;
	vector<vector<ll>> dp;

public:
	void solve(std::istream& in, std::ostream& out) {
		in >> N;
		a.resize(N + 1);
		pref.resize(N + 1, 0);
		for (int i = 1; i <= N; i++) {
			in >> a[i];
			pref[i] = pref[i - 1] + a[i];
		}
		dp.resize(N + 1, vector<ll> (N + 1, -1));
		ll ans = rec(1, N);
		out << ans;
	}

	ll rec(int l, int r) {
		if (l >= r) return 0;
		if (dp[l][r] != -1) return dp[l][r];
		dp[l][r] = 1e18;
		for (int i = l; i < r; i++) {
			s_min(dp[l][r], rec(l, i) + rec(i + 1, r));
		}
		dp[l][r] = dp[l][r] + pref[r] - pref[l - 1];
		return dp[l][r];
	}
};

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	TaskN solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
