#include <bits/stdc++.h>
using namespace std;

void solve(std::string S)
{
    long long ssize = S.size();
    for (int i = 0; i < ssize; i++)
    {
        cout << "x";
    }
    cout << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
