/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class BHinaArare {
public:
	void solve(std::istream& in, std::ostream& out) {
    set<char> set;
    int n;
    in >> n;
    REP(i,n){
      char s;
      in >> s;
      set.insert(s);
    }
    out << (set.size() == 3 ? "Three" : "Four") << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BHinaArare solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
