#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<std::string> S){
    bool y_flag = false;
    // for (int i=0; i<N; i++) {
    //     if (S[i] == "Y") {
    //         y_flag = true;
    //         break;
    //     }
    // }
    for (auto s: S) {
        if (s == "Y") {
            y_flag = true;
            break;
        }
    }
    if (y_flag) cout << "Four" << endl; else cout << "Three" << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<std::string> S(N);
    for(int i = 0 ; i < N ; i++){
        std::cin >> S[i];
    }
    solve(N, std::move(S));
    return 0;
}
