/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author rahdirigs
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

template <typename T> void add(T& a, T b, int mod) {
	a += b;
	if (a >= mod)
		a -= mod;
}

const int mod = 1e9 + 7;

class TaskO {
public:
	int N;
	vector<vector<int>> a;
	vector<vector<ll>> dp;

	void solve(std::istream& in, std::ostream& out) {
		in >> N;
		a.resize(N, vector<int> (N));
		dp.resize(N, vector<ll> (1 << N, -1));
		for (int i = 0; i < N; i++) {
			for (int j = 0; j < N; j++) {
				in >> a[i][j];
			}
		}
		ll ans = rec(0, (1 << N) - 1);
		out << ans;
	}

	ll rec(int m, int w) {
		if (m == N) {
			if (w == 0) return 1;
			return 0;
		}
		if (dp[m][w] != -1) return dp[m][w];
		ll tot = 0;
		for (int i = 0; i < N; i++) {
			int woman = 1 << i;
			bool yes = false;
			if (woman & w) yes = true;
			if (yes && a[m][i]) add(tot, rec(m + 1, w ^ woman), mod);
		}
		return dp[m][w] = tot;
	}
};

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	TaskO solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
