/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

#define REP(i,x,y) for(int i=(x);i<(y);i++)
#define RREP(i,x,y) for(int i=(y)-1;i>=(x);i--)
#define all(x) (x).begin(),(x).end()
//#define int long long

using namespace std;

// conversion
inline int toInt(string s) {int v; istringstream sin(s);sin>>v;return v;}
template<class T> inline string toString(T x) {ostringstream sout;sout<<x;return sout.str();}

#define dump(x)  cout << #x << " = " << (x) << endl
#define debug(x) cout << #x << " = " << (x) << " (L" << __LINE__ << ")" << " " << __FILE__ << endl

typedef long long ll;

const ll MOD = 1e9 + 7;

class FManySlimes {
public:
    void solve(std::istream& in, std::ostream& out) {
        int N;
        in >> N;
        int num = 1 << N;
        vector<int> S(num);
        REP(i,0,num) {
            in >> S[i];
            S[i] *= -1;
        }
        multiset<int> slimes(all(S)), created;
        created.insert(*slimes.begin());
        slimes.erase(slimes.begin());

        REP(i,0,N) {
            vector<int> candidates;
            for (const int slime : created) {
                const auto itr = slimes.upper_bound(slime);
                if (itr == slimes.end()) {
                    out << "No" << "\n";
                    return;
                }
                candidates.push_back(*itr);
                slimes.erase(itr);
            }
            for (const int candidate : candidates) created.insert(candidate);
        }
        out << "Yes" << "\n";
    }
};


int main() {
	FManySlimes solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
