#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;

// Sieve of Eratosthenes
// https://youtu.be/UTVg7wzMWQc?t=2774
struct Sieve {
  int n;
  vector<int> f, primes;
  Sieve(int n=1):n(n), f(n+1) {
    f[0] = f[1] = -1;
    for (ll i = 2; i <= n; ++i) {
      if (f[i]) continue;
      primes.push_back(i);
      f[i] = i;
      for (ll j = i*i; j <= n; j += i) {
        if (!f[j]) f[j] = i;
      }
    }
  }
  bool isPrime(int x) { return f[x] == x;}
  vector<int> factorList(int x) {
    vector<int> res;
    while (x != 1) {
      res.push_back(f[x]);
      x /= f[x];
    }
    return res;
  }
  vector<P> factor(int x) {
    vector<int> fl = factorList(x);
    if (fl.size() == 0) return {};
    vector<P> res(1, P(fl[0], 0));
    for (int p : fl) {
      if (res.back().first == p) {
        res.back().second++;
      } else {
        res.emplace_back(p, 1);
      }
    }
    return res;
  }
};

vector<int> ans;
Sieve sieve; 

// bool canAppend(int prime){
//     cerr <<"prime" << prime <<"check" << endl;
//     cerr <<"size=" << ans.size() << endl;
//     for(int i=0;i<ans.size();i++){
     
//         for(int k=i+1;k<ans.size();k++){
//             for(int j=k+1;j<ans.size();j++){
//                 for(int l=j+1;l<ans.size();l++){
//                        cerr <<"i=" <<i <<"k="<<k <<"j="<<j<<"l="<<l<< endl;
//                     int num = ans[i] + ans[j] + ans[k] + ans[l] +prime;
//                     cerr <<"num=" << num <<endl;
//                     if(sieve.isPrime(num)){
//                         cerr << num << "is prime" << endl;
//                        return false; 
//                     }
//                 }

//             }
//         }
//     }
//     return true;
// }


void solve(long long N){
    sieve= Sieve(55555);
   
    int t=0;
    for(int i=0;i<N;i++){
        while(sieve.primes[t]%5 != 1){
            ++t;
        }
        int p = sieve.primes[t];
        ans.push_back(p);
        ++t;

    }
    for(int i=0;i<N;i++){
        cout << ans[i] << endl;
    }

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
