#include <bits/stdc++.h>
#define rep(i, n) for (long long i = 0; i < (n); i++)
#define rrep(i, n) for (long long i = (n)-1; i >= 0; i--)
using namespace std;

// https://github.com/beet-aizu/library/blob/master/graph/bellmanford.cpp
template <typename T>
struct BellmanFord
{
  static constexpr T INF = numeric_limits<T>::max();

  struct edge
  {
    int u, v;
    T w;
    edge() {}
    edge(int u, int v, T w) : u(u), v(v), w(w) {}
  };

  int n;
  vector<vector<int>> G;
  vector<int> used, reach;
  BellmanFord(int n) : n(n), G(n), used(n, 0), reach(n, 1) {}

  vector<edge> es;
  void add_edge(int u, int v, T c)
  {
    es.emplace_back(u, v, c);
    G[u].emplace_back(v);
  }

  vector<T> build(int from, int &neg_loop)
  {
    vector<T> ds(n, INF);
    ds[from] = 0;
    for (int j = 0; j < n; j++)
    {
      bool update = 0;
      for (auto e : es)
      {
        if (!reach[e.u] || !reach[e.v] || ds[e.u] == INF)
          continue;
        if (ds[e.v] > ds[e.u] + e.w)
        {
          ds[e.v] = ds[e.u] + e.w;
          update = 1;
        }
      }
      if (!update)
        break;
      if (j == n - 1)
      {
        neg_loop = 1;
        return ds;
      }
    }
    neg_loop = 0;
    return ds;
  }

  void dfs(int v)
  {
    if (used[v])
      return;
    used[v] = 1;
    for (int u : G[v])
      dfs(u);
  }

  T shortest_path(int from, int to, int &neg_loop)
  {
    for (int i = 0; i < n; i++)
    {
      fill(used.begin(), used.end(), 0);
      dfs(i);
      reach[i] = used[to];
    }
    return build(from, neg_loop)[to];
  }
};
template <typename T>
constexpr T BellmanFord<T>::INF;

void solve(long long N, long long M, std::vector<long long> a,
           std::vector<long long> b, std::vector<long long> c)
{
  BellmanFord<long long> st(N), gl(N), al(N);
  rep(i, M) a[i]--, b[i]--;
  rep(i, M)
  {
    st.add_edge(a[i], b[i], 1);
    gl.add_edge(b[i], a[i], 1);
  }
  int tmp = 0;
  st.build(0, tmp);
  gl.build(N - 1, tmp);
  rep(i, M)
  {
    if (st.reach[a[i]] && gl.reach[b[i]])
      al.add_edge(a[i], b[i], -c[i]);
  }
  int neg_loop = 0;
  long long t = al.shortest_path(0, N - 1, neg_loop);
  if (neg_loop)
  {
    cout << "inf" << endl;
  }
  else
  {
    cout << -t << endl;
  }
}

// Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main()
{
  long long N;
  scanf("%lld", &N);
  long long M;
  scanf("%lld", &M);
  std::vector<long long> a(M);
  std::vector<long long> b(M);
  std::vector<long long> c(M);
  for (int i = 0; i < M; i++)
  {
    scanf("%lld", &a[i]);
    scanf("%lld", &b[i]);
    scanf("%lld", &c[i]);
  }
  solve(N, M, std::move(a), std::move(b), std::move(c));
  return 0;
}
