#include <bits/stdc++.h>
using namespace std;
#include <bits/stdc++.h>
typedef long long ll;

template<typename NodeIdx,typename Cost>
bool bellman_ford(vector<tuple<NodeIdx,NodeIdx,Cost>> &graph, vector<Cost> &d,  NodeIdx start_idx){
    using Edge = tuple<NodeIdx,NodeIdx,Cost> ;
    const Cost INF = numeric_limits<Cost>::max();
    std::fill(d.begin(), d.end(), INF );

    d[start_idx] = 0;
    for (int i=0;i<d.size()*2;i++){
        for (const Edge &e : graph){
            if (d[get<0>(e)] != INF && d[get<1>(e)] > d[get<0>(e)] + get<2>(e) ){
                d[get<1>(e)] = d[get<0>(e)] + get<2>(e);
                if (i == d.size()-1) d[get<1>(e)]= INF;
                if (i== d.size()*2-1 && get<1>(e) == d.size()-1) return true;
            }
        }
        
    }
    return false;
    
}

void solve(long long N, long long M, std::vector<long long> a, std::vector<long long> b, std::vector<long long> c){
    vector<tuple<ll,ll,ll>> graph;
    for (ll i=0;i<M;i++){
        graph.push_back(make_tuple(a[i]-1,b[i]-1,-c[i]));
    }
    vector<ll> d(N);
    bool ret = bellman_ford<ll,ll>(graph,d,0);
    if (ret){
        printf("inf\n");
    }else{
        printf("%lld\n",-d.back());
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> a(M);
    std::vector<long long> b(M);
    std::vector<long long> c(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&a[i]);
        scanf("%lld",&b[i]);
        scanf("%lld",&c[i]);
    }
    solve(N, M, std::move(a), std::move(b), std::move(c));
    return 0;
}
