/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <bitset>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(ll i = 0; i < (ll)(n); i++)
#define all(v) v.begin(), v.end()

ll GCD(ll a, ll b) { if(b==0) return a; else return GCD(b, a%b); }
ll LCM(ll a, ll b) { return a/GCD(a,b)*b; }

class AFiveAntennas {
public:
	void solve(std::istream& in, std::ostream& out) {
	    vector<int> a(5);
	    rep(i,5) in>>a[i];
	    int k;in>>k;
	    int ma =0;
        for (int j = 0; j < 5; ++j) {
            for (int i = j+1; i < 5; ++i) {
                ma = max(ma, a.at(i)-a.at(j));
            }
        }
        if(ma>k) out<<":("<<endl;
        else out<<"Yay!"<<endl;

	}
};


int main() {
	AFiveAntennas solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
