#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

template<typename T, T F(T, T)>
struct BIT {
    T init;
    vector<T> x;
    BIT(ll n, ll init) : init(init), x(n, init) {}

    // i より小さな位置の要素の最大値を取得する
    T get(ll i){
        ll s = init;
        while(i > 0){
            s = F(s, x.at(i - 1));
            i -= i & (-i);
        }
        return s;
    }

    // i 番目に v を設定する
    void set(ll i, T v){
        i += 1;
        while(i <= x.size()){
            x.at(i - 1) = F(x.at(i - 1), v);
            i += i & (-i);
        }
    }
};

ll max_op(ll a, ll b){ return max(a, b); }
ll min_op(ll a, ll b){ return min(a, b); }

void solve(long long N, std::vector<long long> a){
    REP(i, N){ a.at(i)--; }

    vector<ll> left(N);
    BIT<ll, max_op> maxbit(N, -1);
    REP(i, N){
        left.at(i) = maxbit.get(a.at(i)) + 1;
        maxbit.set(a.at(i), i);
    }

    vector<ll> right(N);
    BIT<ll, min_op> minbit(N, N);
    for(ll i = N - 1; i >= 0; --i){
        right.at(i) = minbit.get(a.at(i)) - 1;
        minbit.set(a.at(i), i);
    }

    ll ans = 0;
    REP(i, N){
        ans += (a.at(i) + 1) * (i - left.at(i) + 1) * (right.at(i) - i + 1);
    }
    cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> a(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&a[i]);
    }
    solve(N, std::move(a));
    return 0;
}
