#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

const string YES = "Yes";
const string NO = "No";

void solve(long long N, long long A, long long B, string S) {
    ll pass = 0;
    ll b_rank = 0;
    for (ll i = 0; i < N; i++) {
        if (S[i] == 'a' && pass < A + B) {
            cout << YES << endl;
            pass++;
        } else if (S[i] == 'b') {
            b_rank++;
            if (pass < A + B && b_rank <= B) {
                cout << YES << endl;
                pass++;
            } else {
                cout << NO << endl;
            }
        } else {
            cout << NO << endl;
        }
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  cin >> N;
  long long A;
  cin >> A;
  long long B;
  cin >> B;
  string S;
  cin >> S;
  solve(N, A, B, S);
  return 0;
}
