#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
    if (a > b) {
        a = b;
        return 1;
    }
    return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
    if (a < b) {
        a = b;
        return 1;
    }
    return 0;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
    pair<pair<string, int>, int> p[110];

    long long N;
    cin >> N;
    vector<string> S(N);
    vector<long long> P(N);
    for (int i = 0; i < N; i++) {
        cin >> S[i];
        cin >> P[i];
        p[i] = make_pair(make_pair(S[i], -P[i]), i);
    }
    sort(p, p+N);

    for (int i = 0; i < N; i++) {
        printf("%d\n", p[i].second+1);
    }

    return 0;
}
