/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <bitset>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(ll i = 0; i < (ll)(n); i++)
#define all(v) v.begin(), v.end()

class C4Adjacent {
public:
	void solve(std::istream& in, std::ostream& out) {
        ll n;
        in>>n;

        ll nd=0,th=0,ks=0;
        rep(i,n){
            ll tmp;
            in>>tmp;
            if(tmp%4==0)  ++th;
            else if(tmp%2==0) ++nd;
            else ++ks;


        }
        if(nd>=2) {
            nd -= (nd / 2) * 2;
        }
        ks += nd;
        if(th+1>=ks) out<<"Yes"<<endl;
        else out<<"No"<<endl;

	}
};


int main() {
	C4Adjacent solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
