#include <bits/stdc++.h>
using namespace std;

const string NO = "IMPOSSIBLE";

void solve(long long A, long long B){
    long long X,K;
    X = A + B;
    K = (A+B)/2;
    if (A - B == 0)
        cout << 0 << endl;
    else if(X==K*2)
        cout << K << endl;
    else
        cout << "IMPOSSIBLE" << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    solve(A, B);
    return 0;
}
