/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author alireza_kaviani
 */

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template<class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;

typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<double, double> pdd;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define SZ(x)                       ll(x.size())

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 3e5 + 10;
const ll LOG = 22;
const ll INF = 8e18;
const ll MOD = 1e9 + 7; // 998244353; // 1e9 + 9;

ll H, W, A, B, ans, fact[MAXN], inv[MAXN];

ll C(ll r, ll n) {
    if (r < 0 || r > n || n < 0) return 0;
    return fact[n] * inv[r] % MOD * inv[n - r] % MOD;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);

    fact[0] = 1;
    for (ll i = 1; i < MAXN; i++) fact[i] = fact[i - 1] * i % MOD;
    for (ll i = 0; i < MAXN; i++) inv[i] = poww(fact[i], MOD - 2, MOD);

    cin >> H >> W >> A >> B;
    ans = C(W - 1, H + W - 2);
    for (ll i = A; i >= 1; i--) {
        ll x = C(i - 1, W - B + i - 1) * (C(B - 1, H - i + B - 1) - (i != A ? 1 : 0) * C(B - 1, H - i + B - 2));
        x = (x % MOD + MOD) % MOD;
        ans = (ans - x + MOD) % MOD;
    }
    cout << ans << endl;

    return 0;
}
/*

*/
