/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: alireza_kaviani
 * Time: 2020-05-22 10:17:29
**/
#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update>;

typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<int, int> pii;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define SZ(x)                       ll(x.size())

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 1e6 + 10;
const ll LOG = 22;
const ll INF = 8e18;
const ll MOD = 1e9 + 7; // 998244353; // 1e9 + 9;

int n , m , q , psS[2][MAXN] , psT[2][MAXN];
string s , t;

int main() {
    ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
    
    cin >> s >> t >> q; 
    n = SZ(s) , m = SZ(t);
    s = "." + s , t = "." + t;
    for(int i = 1 ; i <= n ; i++){
        int ind = s[i] - 'A';
        psS[ind][i] = psS[ind][i - 1] + 1;
        psS[1 - ind][i] = psS[1 - ind][i - 1];
    }
    for(int i = 1 ; i <= m ; i++){
        int ind = t[i] - 'A';
        psT[ind][i] = psT[ind][i - 1] + 1;
        psT[1 - ind][i] = psT[1 - ind][i - 1];
    }

    while(q--){
        int l1 , r1 , l2 , r2 , A , B;
        cin >> l1 >> r1 >> l2 >> r2; l1--; l2--;
        A = psS[0][r1] - psS[0][l1] - psS[1][r1] + psS[1][l1]; A = (A % 3 + 3) % 3;
        B = psT[0][r2] - psT[0][l2] - psT[1][r2] + psT[1][l2]; B = (B % 3 + 3) % 3;
        cout << (A == B ? "YES" : "NO") << endl;
    }

    return 0;
}
/*

*/
