#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(long long N, std::vector<long long> p){
  for(long long i = 1; i < N; i++){
    if(p[i-1] > p[i]) goto nosort;
  }

  cout << YES << endl;
  return;

  nosort:
  for(long long i = 0; i < N; i++){
    for(long long j = (i+1); j < N; j++){
      vector<long long> vec = p;
      long long tmp;
      tmp = vec[i];
      vec[i] = vec[j];
      vec[j] = tmp;
      for(long long k = 1; k < N; k++){
        if(vec[k-1] > vec[k]) goto nosort2;
      }

      cout << YES << endl;
      return;
      nosort2:
      continue;
    }
  }


  cout << NO << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> p(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&p[i]);
  }
    solve(N, std::move(p));
    return 0;
}
