/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author CompuWare
 */

#include <iostream>
#include <fstream>

#include <iostream>

using namespace std;

class ASecurity {
public:
    void solve(std::istream &in, std::ostream &out) {
        string s;
        in >> s;
        for (int i = 1; i < s.size(); i++) {
            if (s[i] == s[i - 1]) {
                out << "Bad";
                return;
            }
        }
        out << "Good";
    }
};


int main() {
    ASecurity solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
