/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(int i = 0; i < (int)(n); i++)
#define all(v) v.begin(), v.end()

class ASecurity {
public:
	void solve(std::istream& in, std::ostream& out) {
        string s;
        in>>s;
        rep(i,3){
            if(s.at(i)==s.at(i+1)) {
                out<<"Bad";
                return;
            }
        }
        out<<"Good";
	}
};


int main() {
	ASecurity solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
