#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> a){
  sort(a.begin(), a.end(), greater<long long>());

  long long acc = 0;
  for(long long i = 0; i < N; i++){
    acc += a[(i*2)+1];
  }

  cout << acc << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> a(3*N);
  for(int i = 0 ; i < 3*N ; i++){
    scanf("%lld",&a[i]);
  }
    solve(N, std::move(a));
    return 0;
}
