#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long C, long long X, long long Y){
  long long mymin = INT_MAX;

  for(long long i = 0; i <= 100000; i++) {
    mymin = min(mymin, i * (2 * C) + max(0ll, X - i) * A + max(0ll, Y - i) * B);
  }

  cout << mymin << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long C;
  scanf("%lld",&C);
  long long X;
  scanf("%lld",&X);
  long long Y;
  scanf("%lld",&Y);
    solve(A, B, C, X, Y);
    return 0;
}
