/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define RFOR(i, a, b) for(int i = (int)(b-1);i>=(int)(a);--i)
#define REP(i, n)  FOR(i,0,(n))
typedef vector<int> vec;


class BTollGates {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n, m, x;
      in >> n >> m >> x;
      x--;
      vector<int> a(m);
      REP(i, m) {
        in >> a[i];
        a[i]--;
      }
      vec b(n, 0);
      REP(i, m) {
        b[a[i]]++;
      }
      int front = 0, back = 0;
      FOR(i, x, n) {
        front += b[i];
      }
      RFOR(i, 0, x) {
        back += b[i];
      }
      int min_c = min(front, back);
      out << min_c << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BTollGates solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
