#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(long long N, long long M, long long X, vector<long long> A) {
    ll min_cost = 1e8;

    ll tmp_cost = 0;
    for (int i = X-1; i <= N; i++) {
        for (int m = 0; m < M; m++) {
            if (i == A[m]-1) tmp_cost++;
        }
    }
    if (min_cost > tmp_cost) min_cost = tmp_cost;

    tmp_cost = 0;
    for (int i = X-1; i >= 0; i--) {
        for (int m = 0; m < M; m++) {
            if (i == A[m]-1) tmp_cost++;
        }
    }
    if (min_cost > tmp_cost) min_cost = tmp_cost;

    cout << min_cost << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  cin >> N;
  long long M;
  cin >> M;
  long long X;
  cin >> X;
  vector<long long> A(M);
  for (int i = 0; i < M; i++) {
    cin >> A[i];
  }
  solve(N, M, X, move(A));
  return 0;
}
