#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG

bool isOk(vec<ll>& D, int diff){
    int lTop = 0;
    int rTop = 0;
    for(auto d: D){
        int lGap = d - lTop;
        int rGap = d - rTop;
        if(lGap < diff && rGap < diff){
            // impossible
            return false;
        }else if(lGap >= diff && rGap >= diff){
            // できるだけ後半をのこしておく。すすんでいる方をつぶす
            if(lTop >= rTop){
                // 左におく
                lTop = d;
            }else{
                rTop = d;
            }
        }else if(lGap >= diff){
            // 左におくしかない
            lTop = d;
        }else{
            // 右におくしかない
            rTop = d;
        }
        // 末尾が大丈夫か確認する
        int finalGap = 24 - lTop - rTop;
        if(finalGap < diff){
            // だめだった
            return false;
        }
    }
    return true;
}

void solve(long long N, std::vector<long long> D){
    sort(D.begin(), D.end());
    for(int i=12; i >= 0; i--){
        if(isOk(D, i)){
            cout << i << endl;
            break;
        }
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> D(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&D[i]);
    }
    solve(N, std::move(D));
    return 0;
}
