#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

ll dist(ll x, ll y){
    return min(abs(x - y), 24 - abs(x - y));
}

void solve(long long N, std::vector<long long> D){
    D.push_back(0); // Add takahashi
    ll ans = 0;
    for(ll i = 0; i < (1 << 11); ++i){
        vector<ll> tmp(24, 0);
        REP(j, D.size()){
            if(D.at(j) == 0){
                tmp.at(0)++;
            }else if(D.at(j) == 12){
                tmp.at(12)++;
            }else{
                if(tmp.at(D.at(j)) == 0 && tmp.at(24 - D.at(j)) == 0){
                    if((i >> (D.at(j) - 1)) & 1){
                        tmp.at(D.at(j))++;
                    }else{
                        tmp.at(24 - D.at(j))++;
                    }
                }else if(tmp.at(D.at(j)) == 0){
                    tmp.at(D.at(j))++;
                }else if(tmp.at(24 - D.at(j)) == 0){
                    tmp.at(24 - D.at(j))++;
                }else{
                    cout << 0 << endl;
                    return;
                }
            }
        }

        ll mindiff = 24;
        REP(k, tmp.size()){
            if(tmp.at(k) == 0){ continue; }
            if(tmp.at(k) >= 2){
                mindiff = 0;
                break;
            }
            for(ll l = k + 1; l < tmp.size(); ++l){
                if(tmp.at(l) == 0){ continue; }
                mindiff = min(mindiff, dist(k, l));
            }
        }
        ans = max(ans, mindiff);
    }
    cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> D(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&D[i]);
    }
    solve(N, std::move(D));
    return 0;
}
