/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <fstream>

#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <bitset>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(ll i = 0; i < (ll)(n); i++)
#define all(v) v.begin(), v.end()

ll GCD(ll a, ll b) {
    if(b==0) return a;
    else return GCD(b, a%b);
}

ll LCM(ll a, ll b) {
    return a/GCD(a,b)*b;
}

class CMarch {
public:
	void solve(std::istream& in, std::ostream& out) {
        ll n;in>>n;
        vector<ll> cnt(5);
        rep(i,n){
            string s;
            in>>s;
            if(s[0]=='M') ++cnt[0];
            else if (s[0]=='A') ++cnt[1];
            else if (s[0]=='R') ++cnt[2];
            else if (s[0]=='C') ++cnt[3];
            else if (s[0]=='H') ++cnt[4];
        }
        ll ans=0;
        for(int i=0; i<5; ++i){
            for(int j=i+1; j<5; ++j){
                for(int k=j+1; k<5; ++k){
                    ans+=cnt[i]*cnt[j]*cnt[k];
                }
            }
        }
        out<<ans<<endl;
	}
};


int main() {
	CMarch solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
