/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))
typedef vector<int> vec;


class CMarch {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    map<char, int> m;
    REP(i,n){
      string s;
      in >> s;
      m[s[0]]++;
    }
    const char a[] = {'M', 'A', 'R', 'C', 'H'};
    const int p[] = {0, 0, 0, 0, 0, 0, 1, 1, 1, 2};
    const int q[] = {1, 1, 1, 2, 2, 3, 2, 2, 3, 3};
    const int r[] = {2, 3, 4, 3, 4, 4, 3, 4, 4, 4};
    int res = 0;
    vec d = {m[a[0]], m[a[1]], m[a[2]], m[a[3]], m[a[4]]};
    REP(i, 10){
      res += d[p[i]] * d[q[i]] * d[r[i]];
    }
    out << res << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	CMarch solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
