#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long A, long long B, std::vector<long long> X){
  long long res = 0;
  for (int i = 1; i < N; i++) {
    res += min(A*(X[i]-X[i-1]), B);
  }
  cout << res << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    std::vector<long long> X(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&X[i]);
    }
    solve(N, A, B, std::move(X));
    return 0;
}
