/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define rep(i, n)           for (int i = 0; i < (int)(n); i++)
#define REP(i, a, b)        for (int i = (int)(a); i < (int)(b); i++)
#define FOR(i, a)           for (auto &i : a)
#define ALL(obj)            begin(obj), end(obj)
#define MAX(x)              *max_element(ALL(x))
#define MIN(x)              *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl                endl

using namespace std;
const int MOD   = (int)(1e9 + 7);
const int INF   = (int)(1e13 + 7);
const double PI = acos(-1);

int CEIL(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); } //ceil() for int
int mod(int a, int b) { return a >= 0 ? a % b : a - (b * CEIL(a, b)); }             //always return positive num
int pow(int x, int y) {                                                             //return x^y in order(log(y))
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}
template <class T>
void cumulative_sum(T &container) {
  for (int i = 0; i < container.size() - 1; i++) container[i + 1] += container[i];
}

class DColoringEdgesOnTree {
public:
  static void solve(istream &cin, ostream &cout) {
    int N;
    cin >> N;
    vector<int> color(N, 0);
    vector<pair<int, int>> edge(N - 1);
    vector<vector<pair<int, int>>> edge2(N);
    map<int, int> ans;
    rep(i, N - 1) {
      int a, b;
      cin >> a >> b;
      color[a - 1]++;
      color[b - 1]++;
      edge[i] = {a - 1, b - 1};
      edge2[a - 1].emplace_back(b - 1, i);
      edge2[b - 1].emplace_back(a - 1, i);
    }
    cout << MAX(color) << endl;
    deque<pair<int, int>> pos = {{0, 0}};
    vector<int> check(N, 0);
    check[0] = 1;
    while (pos.size()) {
      int now  = pos[0].first;
      int used = pos[0].second;
      pos.pop_front();
      int i = 0;
      rep(j, edge2[now].size()) {
        if (check[edge2[now][j].first]) continue;
        i++;
        if (i == used) i++;
        check[edge2[now][j].first] = 1;
        ans[edge2[now][j].second]  = i;
        pos.emplace_back(edge2[now][j].first, i);
      }
    }
    rep(i, N - 1) {
      cout << ans[i] << endl;
    }
  }
};


signed main() {
  cin.tie(0);
  ios::sync_with_stdio(false);
  DColoringEdgesOnTree solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
