#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> V, std::vector<long long> C){
  long long acc = 0;
  for(long long i = 0; i < N; i++){
    if(V[i] - C[i] > 0) acc += (V[i] - C[i]);
  }

  cout << acc << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> V(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&V[i]);
  }
  std::vector<long long> C(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&C[i]);
  }
    solve(N, std::move(V), std::move(C));
    return 0;
}
