#include <bits/stdc++.h>
using namespace std;

void solve(std::string s)
{
    long long S_size = s.size();
    cout << s[0] << S_size - 2 << s[S_size - 1] << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string s;
    std::cin >> s;
    solve(s);
    return 0;
}
