/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
typedef pair<int, int> P;


class DIslandsWar {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n, m;
      in >> n >> m;
      vector<P> ab(m);
      REP(i, m) {
        int x, y;
        in >> x >> y;
        ab[i] = P(x, y);
      }
      sort(ab.begin(), ab.end(), [](P a, P b) {
          return a.second < b.second;
      });
      //tは前回採用した区間の終端
      int t = 0, ans = 0;
      REP(i, m) {
        if (t <= ab[i].first) {//前回採用した区間の終端と調べる区間の始端を比較
          ans++;
          t = ab[i].second;
        }
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  DIslandsWar solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
