#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

ll p2(ll x){
    ll ret = 1;
    for(; ret <= x; ret *= 2){
    }
    return ret;
}

void solve(long long N, std::vector<long long> A){
    multiset<ll> s;
    REP(i, A.size()){
        s.insert(A.at(i));
    }
    ll ans = 0;
    while(s.size()){
        const ll x = *s.rbegin();
        s.erase(s.find(x));
        const ll y = p2(x);
        auto it = s.find(y - x);
        if(it != s.end()){
            ans++;
            s.erase(it);
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
