/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include<bits/stdc++.h>
using namespace std;

#define rep(i,n) for(int64_t i = 0;i < n;i++)
using ll = int64_t;
template<class T> bool chmin(T& a,T b){
    if(a > b){ a = b; return true; }else return false;
}
template<class T> bool chmax(T& a,T b){
    if(a < b){ a = b; return true; }else return false;
}


class CColorfulLeaderboard {
public:
	void solve(std::istream& cin, std::ostream& cout) {
        cin.tie(0);
        ios::sync_with_stdio(false);
        cout << fixed << setprecision(20);

        vector<int64_t > col(9,0);

        int64_t n;cin >> n;
        rep(i,n){
            int64_t foo;cin >> foo;
            if(foo >= 3200)col[8]++;
            else col[foo / 400]++;
        }

        int64_t mn = 0,mx = 0;

        rep(i,8) mn += (col[i] >= 1);
        mx = mn + col[8];
        if(mn == 0) mn = 1;

        cout << mn << ' ' << mx << '\n';

        //int t;cin >> t;rep(i,t)main2(cin,cout);
	}
	void main2(istream& cin,ostream& cout){

	}
};


int main() {
	CColorfulLeaderboard solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
